import { Language } from './types';

export const translations: Record<Language, Record<string, string>> = {
  English: {
    // Nav & Shell
    home: "Home",
    diagnosis: "Diagnosis",
    assistant: "Assistant",
    insights: "Insights",
    market: "Market",
    mission: "Mission",
    online: "Online",
    offline: "Offline",
    logout: "Logout",
    backToHome: "Back to Home",
    chooseLanguage: "Choose State Language",
    languageSuffix: "Language",
    namaste: "Namaste",
    farmOverviewFor: "Here is your farm state overview for",
    offlineModeActive: "Offline Mode Active",
    offlineModeDesc: "You are currently disconnected or simulating offline mode. Critical weather, crop metrics, and market indices are loaded from local storage cache. Offline Leaf Diagnostics is enabled with high-probability matches.",
    
    // Landing Page
    landingTitle: "Cultivating the Future of India's Farming",
    landingSubtitle: "Bridging ancient agricultural wisdom with server-side AI precision to safeguard Indian livelihoods and yields.",
    startFarming: "Start Farming",
    features: "Features",
    howItWorks: "How it Works",
    successStories: "Success Stories",
    ourMission: "Our Mission",
    aiCropDoctor: "AI Crop Doctor",
    aiCropDoctorDesc: "Instantly diagnose crop diseases with your phone camera and receive certified organic & chemical prescriptions.",
    hyperLocalWeather: "Hyper-local Weather",
    hyperLocalWeatherDesc: "Receive real-time micro-climate metrics, soil telemetry, and spray suitability advisories optimized for your region.",
    mandiPrices: "Mandi Prices",
    mandiPricesDesc: "Stay ahead with transparent price indices from your local APMC Mandis and calculate crop profitability seamlessly.",
    voiceAssist: "Voice Assist",
    voiceAssistDesc: "Listen to scientific farming advice in your native regional language with automated clear voice assistance.",
    
    // Login Screen
    farmerLogin: "Farmer Login",
    enterPhone: "Enter your phone number",
    sendOtp: "Send OTP",
    verifyOtp: "Verify OTP",
    agreeTerms: "By continuing, you agree to our Terms of Service & Privacy Policy.",
    phonePlaceholder: "Enter 10-digit mobile number",
    otpSent: "OTP has been sent to your number",
    verifyAndLogin: "Verify & Login",

    // Language Step
    onboardingChooseLanguage: "Choose Your Language",
    onboardingChooseLanguageDesc: "Select your native language for personalized agronomist advisory, market insights, and voice guidance.",
    detectingLocation: "Detecting farm coordinates...",
    locationDetected: "Farm location detected successfully",
    nextStep: "Next Step",

    // Crop Step
    whatAreYouGrowing: "What are you growing?",
    selectCropsDesc: "Select your current cultivated crops to tailor your diagnostic prescriptions, weather indices, and market trends.",
    back: "Back",

    // Profile Step
    completeProfile: "Complete Farmer Profile",
    enterName: "Enter your name",
    enterNamePlaceholder: "e.g., Ramesh Kumar",
    voiceGuided: "Voice-Guided Assistance",
    voiceGuidedDesc: "Automatically read out diagnostic prescriptions and weather warnings in my regional language",
    submitEnterFarm: "Submit & Enter Farm",

    // Dashboard
    liveFarmClimate: "Live Farm Climate",
    overcastClouds: "Overcast Clouds",
    humidity: "Humidity",
    wind: "Wind",
    uvIndex: "UV Index",
    spraySuitability: "Spray Suitability",
    highIdeal: "HIGH / IDEAL",
    sprayAdvisoryText: "Wind speed is gentle (8 km/h) and temperature is below 35°C. Humidity is favorable. Perfect time to apply foliar nutrients or bio-fungicide!",
    targetHours: "Target Hours",
    cropHealthStatus: "Primary Crop Health Status",
    diagnoseLeaf: "Diagnose Leaf",
    consultExpert: "Consult Expert",
    status: "Status",
    yield: "Yield",
    estimatedValue: "Estimated Value",
    riskIndex: "Risk Index",
    healthy: "Healthy",
    yellowLeafWarn: "Yellow Leaf Warnings",
    lowRisk: "Low Risk",
    mediumRisk: "Medium Risk",
    highRisk: "High Risk",
    cropAdvisoryPrescription: "Crop Advisory & Prescriptions",
    advisoryAlert: "Heavy rainfall predicted in 48 hours. Postpone urea top dressing to avoid run-off.",
    todayAction: "Today's Action Plan",
    advisoryAction1: "Ensure standing water depth of 2-3 inches for paddy tillering.",
    advisoryAction2: "Inspect lower crop canopy for early signs of blast or leaf spots.",
    activeCropTrack: "Active Crop Track",
    cultivatedCrop: "Cultivated Crop",
    yieldPrediction: "Yield Prediction",
    estimatedMarketValue: "Estimated Market Value",
    checkMandiRates: "Check Mandi Rates",
    optimalIrrigation: "Optimal Irrigation",
    irrigationAdvisoryText: "Clay-loam moisture level is currently 32%. No irrigation needed for the next 48 hours. Rainfall of 4.5mm is expected on Friday.",
    viewMoistureChart: "View Moisture Chart",
    nitrogenUreaLevel: "Nitrogen / Urea Level",
    nitrogenAdvisoryText: "Last scans indicate healthy chlorophyll. Standard top dressing with 20 kg Urea per acre is recommended post irrigation in week 4.",
    askCropAssistant: "Ask Crop Assistant",
    outbreakPestForecast: "Outbreak Pest Forecast",
    regionalStemBorerWarning: "Regional Stem Borer Warning",
    stemBorerAdvisoryText: "High humidity creates favorable conditions for stem borer. Outbreak risk is: ",
    initiateAiLeafScan: "Initiate AI Leaf Scan Now",
    smartFarmTodos: "Smart Farm To-Dos",
    scanWestLeafZone: "Scan West Leaf Zone",
    pendingScan: "Pending Scan",
    scanButton: "Scan",
    addUreaTopdress: "Add 20kg Urea top-dress",
    sowingWeek4: "Sowing Week 4",
    week4Label: "Week 4",
    dailyUpdate: "Daily Update",
    whatToPlantNext: "What to Plant Next?",
    durumWheat: "Durum Wheat",
    optimalSowing: "Optimal Sowing:",
    novemberRabi: "November (Rabi Season)",
    estimatedDemand: "Estimated Demand:",
    veryHigh: "Very High (+12%)",
    durumWheatAdvisoryText: "Due to lower global stocks, premium durum varieties are expected to trade 15% above MSP at Khanna and Indore mandis. Recommended variety: HD 3086.",

    // Weather Insights
    weatherSoilInsights: "Weather & Soil Insights",
    weatherSoilDesc: "Hyper-local climate advisory, soil telemetry, and predictive forecasting",
    liveSynced: "Live Synced",
    offlineCache: "Viewing Offline Cache",
    syncWeather: "Sync Weather",
    syncing: "Syncing...",
    syncSuccessWeather: "Fasal database refreshed. Weather advisories and soil telemetry updated successfully in your local storage cache.",
    rainAdvisory: "Smart Rain Advisory Banner",
    heavyRainAlert: "Heavy Rain Warning (78mm) expected in 2 days. Secure irrigation channels immediately.",
    soilTelemetry: "Soil Telemetry",
    soilMoisture: "Soil Moisture",
    soilTemp: "Soil Temperature",
    statusFavorable: "Status: Favorable",
    idealForTillering: "Ideal for tillering",
    sevenDayForecast: "7-Day Weather & Spray Suitability Forecast",
    day: "Day",
    temp: "Temp",
    condition: "Condition",
    rainProb: "Rain Prob.",
    windSpeed: "Wind Speed",

    // Diagnosis Screen
    aiCropScanner: "AI Crop Diagnostic Scanner",
    aiCropScannerDesc: "Capture or upload diseased plant leaves. Our server-side Gemini AI instantly detects pathogens and compiles prescriptions.",
    offlineModelEngaged: "Offline Expert Model Engaged",
    selectCrop: "Select Crop",
    describeSymptoms: "Describe Symptoms (Optional)",
    describeSymptomsPlaceholder: "e.g., small brown spots on leaves, yellowing of borders, powdery white mold...",
    uploadLeafImage: "Upload Leaf Image",
    dragDropOrClick: "Drag & drop leaf photo here, or click to browse",
    runningDiagnostic: "Running Diagnostic Prescription...",
    analyzingFoliage: "Analyzing foliage patterns & matching agronomic expert rules...",
    geminiAiAgronomist: "Gemini AI Agronomist",
    offlineLocalHeuristics: "Offline Local Heuristics",
    localExpertPrescription: "Local Expert Prescription",
    diagnosticPrescriptionSheet: "Diagnostic Prescription Sheet",
    analysisConfidence: "Disease Confidence Score",
    symptoms: "Observed Symptoms",
    causes: "Pathogen & Trigger Causes",
    treatment: "Scientific Treatment & Management",
    organic: "Organic Treatment",
    chemical: "Chemical Treatment",
    prevention: "Long-Term Prevention Strategy",
    sampleDiseasedPhotos: "Or click a sample photo to simulate a disease",

    // Chat Screen
    aiAgronomistExpertChat: "AI Agronomist Expert Chat",
    askFarmingQuestion: "Ask any farming question about pest management, fertilization, or irrigation",
    messagePlaceholder: "Ask about yellowing leaves, fertilizer dosage...",
    typing: "Agronomist is analyzing...",

    // Market Intelligence
    marketIntelMandi: "Market Intelligence & Mandi",
    marketIntelDesc: "Real-time agricultural price indices, APMC Mandi trends, and cost profitability estimators",
    liveIndex: "Live Index",
    syncPrices: "Sync Prices",
    syncSuccessPrices: "Fasal Mandi indices synced and cached successfully in your local storage cache. Offline trading estimations ready.",
    commoditySelector: "Commodity Selector",
    mandiPriceTrends: "APMC Mandi Price Trends",
    mandiName: "Mandi Name",
    currentPrice: "Current Price (per Quintal)",
    dailyChange: "Daily Change",
    profitabilityCalc: "Cultivation Cost & Profitability Calculator",
    acresLabel: "Land Area (in Acres)",
    expectedYieldLabel: "Expected Yield (Quintals/Acre)",
    costPerAcreLabel: "Cultivation Cost (₹/Acre)",
    estimatedRevenue: "Estimated Gross Revenue",
    netProfitMargin: "Net Profit Margin",
    netProfit: "Net Profit",

    // About Us
    ourVisionStory: "Our Vision & Story",
    visionTitle: "Cultivating the Future of India's Farming.",
    visionDesc: "Bridging ancient agricultural wisdom with server-side AI precision to safeguard Indian livelihoods and yields.",
    originStory: "THE ORIGIN STORY",
    fromVisionToVitality: "From Vision to Vitality",
    originDesc1: "Fasal Doctor was born in the agricultural heartlands of Haryana and Punjab. Watching local farmers battle unforeseen weather disasters, pest outbreaks, and opaque market middlemen, we set out to build an advisor that fits directly inside their pockets.",
    originDesc2: "By combining high-fidelity localized weather forecasts with server-side Gemini AI models, we deliver actionable crop-diagnoses and fertilizer prescriptions in moments, removing speculation from farming forever.",
    coreValues: "Core Scientific Pillars",
    value1Title: "Agronomic Integrity",
    value1Desc: "Every chemical or bio-fertilizer advice is clinically structured based on state agricultural university data.",
    value2Title: "Digital Inclusivity",
    value2Desc: "Deep support for multiple regional dialects, clear text, and local language speech outputs for accessibility.",
    value3Title: "Offline Resilience",
    value3Desc: "Our localized matching engine works in deep fields without high-speed cellular networks."
  },
  Hindi: {
    // Nav & Shell
    home: "होम",
    diagnosis: "निदान",
    assistant: "सहायक",
    insights: "मौसम",
    market: "बाज़ार",
    mission: "हमारा उद्देश्य",
    online: "ऑनलाइन",
    offline: "ऑफ़लाइन",
    logout: "लॉगआउट",
    backToHome: "होम पर वापस जाएं",
    chooseLanguage: "राज्य की भाषा चुनें",
    languageSuffix: "भाषा",
    namaste: "नमस्ते",
    farmOverviewFor: "यहाँ आपके खेत की स्थिति का विवरण है",
    offlineModeActive: "ऑफ़लाइन मोड सक्रिय",
    offlineModeDesc: "आप वर्तमान में डिस्कनेक्ट हैं या ऑफ़लाइन मोड का अनुकरण कर रहे हैं। महत्वपूर्ण मौसम, फसल मेट्रिक्स और बाजार सूचकांक स्थानीय भंडारण कैश से लोड किए गए हैं। ऑफ़लाइन लीफ डायग्नोस्टिक्स सक्षम है।",

    // Landing Page
    landingTitle: "भारतीय कृषि के भविष्य को समृद्ध बनाना",
    landingSubtitle: "भारतीय किसानों की आजीविका और पैदावार की सुरक्षा के लिए पारंपरिक कृषि ज्ञान को उन्नत एआई सटीकता के साथ जोड़ना।",
    startFarming: "खेती शुरू करें",
    features: "विशेषताएं",
    howItWorks: "यह कैसे काम करता है",
    successStories: "سफलकी कहानियां",
    ourMission: "हमारा मिशन",
    aiCropDoctor: "एआई फसल डॉक्टर",
    aiCropDoctorDesc: "अपने फोन कैमरे से फसल की बीमारियों का तुरंत निदान करें और प्रमाणित जैविक और रासायनिक उपचार प्राप्त करें।",
    hyperLocalWeather: "स्थानीय मौसम",
    hyperLocalWeatherDesc: "अपने क्षेत्र के अनुकूल वास्तविक समय के सूक्ष्म जलवायु मेट्रिक्स, मिट्टी की नमी और कीटनाशक छिड़काव के लिए उपयुक्त समय की जानकारी प्राप्त करें।",
    mandiPrices: "मंडी भाव",
    mandiPricesDesc: "अपनी स्थानीय एपीएमसी मंडियों के पारदर्शी मूल्य सूचकांकों के साथ हमेशा आगे रहें और फसल की लाभप्रदता की गणना करें।",
    voiceAssist: "आवाज सहायता",
    voiceAssistDesc: "स्वचालित स्पष्ट आवाज सहायता के साथ अपनी मातृभाषा में वैज्ञानिक खेती की सलाह सुनें।",

    // Login Screen
    farmerLogin: "किसान लॉगिन",
    enterPhone: "अपना मोबाइल नंबर दर्ज करें",
    sendOtp: "ओटीपी भेजें",
    verifyOtp: "ओटीपी सत्यापित करें",
    agreeTerms: "आगे बढ़कर, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत होते हैं।",
    phonePlaceholder: "10-अंकीय मोबाइल नंबर दर्ज करें",
    otpSent: "आपके नंबर पर ओटीपी भेज दिया गया है",
    verifyAndLogin: "सत्यापित करें और लॉगिन करें",

    // Onboarding Language Step
    onboardingChooseLanguage: "अपनी भाषा चुनें",
    onboardingChooseLanguageDesc: "व्यक्तिगत कृषि सलाहकार, बाजार अंतर्दृष्टि और आवाज मार्गदर्शन के लिए अपनी मातृभाषा का चयन करें।",
    detectingLocation: "खेत के निर्देशांक का पता लगाया जा रहा है...",
    locationDetected: "खेत का स्थान सफलतापूर्वक मिल गया",
    nextStep: "अगला कदम",

    // Onboarding Crop Step
    whatAreYouGrowing: "आप क्या उगा रहे हैं?",
    selectCropsDesc: "अपनी फसल के निदान, मौसम सूचकांक और बाजार के रुझानों को अनुकूलित करने के लिए अपनी वर्तमान खेती का चयन करें।",
    back: "पीछे",

    // Profile Step
    completeProfile: "किसान प्रोफ़ाइल पूरी करें",
    enterName: "अपना नाम दर्ज करें",
    enterNamePlaceholder: "जैसे, रमेश कुमार",
    voiceGuided: "आवाज-निर्देशित सहायता",
    voiceGuidedDesc: "मेरी क्षेत्रीय भाषा में नैदानिक उपचार और मौसम की चेतावनी स्वतः पढ़कर सुनाएं",
    submitEnterFarm: "जमा करें और खेत में प्रवेश करें",

    // Dashboard
    liveFarmClimate: "लाइव खेत की जलवायु",
    overcastClouds: "आंशिक रूप से बादल",
    humidity: "आर्द्रता",
    wind: "हवा",
    uvIndex: "यूवी सूचकांक",
    spraySuitability: "छिड़काव उपयुक्तता",
    highIdeal: "सर्वोत्तम / उपयुक्त",
    sprayAdvisoryText: "हवा की गति धीमी (8 किमी/घंटा) है और तापमान 35 डिग्री सेल्सियस से कम है। आर्द्रता अनुकूल है। पत्तेदार पोषक तत्व या बायो-फंगीसाइड छिड़कने का सही समय है!",
    targetHours: "लक्ष्य घंटे",
    cropHealthStatus: "मुख्य फसल स्वास्थ्य स्थिति",
    diagnoseLeaf: "पत्ती का निदान करें",
    consultExpert: "विशेषज्ञ से पूछें",
    status: "स्थिति",
    yield: "पैदावार",
    estimatedValue: "अनुमानित मूल्य",
    riskIndex: "जोखिम सूचकांक",
    healthy: "स्वस्थ",
    yellowLeafWarn: "पीली पत्तियों की चेतावनी",
    lowRisk: "कम जोखिम",
    mediumRisk: "मध्यम जोखिम",
    highRisk: "उच्च जोखिम",
    cropAdvisoryPrescription: "फसल सलाह और पर्ची",
    advisoryAlert: "48 घंटों में भारी बारिश की भविष्यवाणी। खाद बहने से बचाने के लिए यूरिया डालने का काम टालें।",
    todayAction: "आज की कार्य योजना",
    advisoryAction1: "धान की कल्ले फूटने के समय 2-3 इंच पानी जमा रखना सुनिश्चित करें।",
    advisoryAction2: "झुलसा रोग या पत्तों के धब्बों के शुरुआती लक्षणों के लिए फसल के निचले हिस्से की जांच करें।",
    activeCropTrack: "सक्रिय फसल विश्लेषण",
    cultivatedCrop: "उगाई गई फसल",
    yieldPrediction: "अनुमानित पैदावार",
    estimatedMarketValue: "अनुमानित बाजार मूल्य",
    checkMandiRates: "मंडी भाव देखें",
    optimalIrrigation: "अनुकूल सिंचाई",
    irrigationAdvisoryText: "मिट्टी की नमी अभी 32% है। अगले 48 घंटों तक सिंचाई की आवश्यकता नहीं है। शुक्रवार को बारिश होने की संभावना है।",
    viewMoistureChart: "नमी चार्ट देखें",
    nitrogenUreaLevel: "नाइट्रोजन और यूरिया का स्तर",
    nitrogenAdvisoryText: "क्लोरोफिल का स्तर सामान्य है। चौथे सप्ताह में प्रति एकड़ 20 किलोग्राम यूरिया का छिड़काव करने की सलाह दी जाती है।",
    askCropAssistant: "फसल सहायक से पूछें",
    outbreakPestForecast: "कीट संक्रमण का पूर्वानुमान",
    regionalStemBorerWarning: "तना छेदक कीट की क्षेत्रीय चेतावनी",
    stemBorerAdvisoryText: "उच्च आर्द्रता कीट संक्रमण के लिए अनुकूल वातावरण बनाती है। संक्रमण का जोखिम: ",
    initiateAiLeafScan: "अभी एआई पत्ती स्कैन शुरू करें",
    smartFarmTodos: "खेत के महत्वपूर्ण कार्य",
    scanWestLeafZone: "पश्चिमी क्षेत्र की पत्तियों को स्कैन करें",
    pendingScan: "स्कैन बाकी है",
    scanButton: "स्कैन",
    addUreaTopdress: "20 किलो यूरिया का छिड़काव करें",
    sowingWeek4: "बुवाई का चौथा सप्ताह",
    week4Label: "चौथा सप्ताह",
    dailyUpdate: "दैनिक अपडेट",
    whatToPlantNext: "आगे क्या बोएं?",
    durumWheat: "गेहूं की उन्नत किस्म",
    optimalSowing: "बुवाई का सही समय:",
    novemberRabi: "नवंबर (रबी सीजन)",
    estimatedDemand: "अनुमानित मांग:",
    veryHigh: "बहुत अधिक (+12%)",
    durumWheatAdvisoryText: "वैश्विक स्तर पर कम स्टॉक के कारण, गेहूं की उन्नत किस्में खन्ना और इंदौर मंडियों में एमएसपी से 15% अधिक भाव पर बिकने की उम्मीद है। अनुशंसित किस्म: एचडी 3086.",

    // Weather Insights
    weatherSoilInsights: "मौसम और मिट्टी की जानकारी",
    weatherSoilDesc: "स्थानीय जलवायु सलाह, मिट्टी का तापमान और नमी और पूर्वानुमान",
    liveSynced: "लाइव सिंक किया गया",
    offlineCache: "ऑफ़लाइन डेटा देखा जा रहा है",
    syncWeather: "मौसम अपडेट करें",
    syncing: "अपडेट हो रहा है...",
    syncSuccessWeather: "फसल डेटाबेस अपडेट किया गया। मौसम की सलाह और मिट्टी की नमी को आपके लोकल कैश में सफलतापूर्वक सुरक्षित कर लिया गया है।",
    rainAdvisory: "स्मार्ट बारिश चेतावनी",
    heavyRainAlert: "2 दिनों में भारी बारिश (78 मिमी) की चेतावनी। सिंचाई चैनलों को तुरंत सुरक्षित करें।",
    soilTelemetry: "मृदा टेलीमेट्री",
    soilMoisture: "मिट्टी की नमी",
    soilTemp: "मिट्टी का तापमान",
    statusFavorable: "स्थिति: अनुकूल",
    idealForTillering: "कल्ले फूटने के लिए आदर्श",
    sevenDayForecast: "7-दिवसीय मौसम और छिड़काव उपयुक्तता पूर्वानुमान",
    day: "दिन",
    temp: "तापमान",
    condition: "मौसम",
    rainProb: "बारिश की संभावना",
    windSpeed: "हवा की गति",

    // Diagnosis Screen
    aiCropScanner: "एआई फसल रोग स्कैनर",
    aiCropScannerDesc: "बीमार पौधे की पत्तियों की तस्वीर खींचें या अपलोड करें। हमारा सर्वर-साइड जेमिनी एआई तुरंत रोग का पता लगाकर पर्ची तैयार करता है।",
    offlineModelEngaged: "ऑफ़लाइन विशेषज्ञ मॉडल सक्रिय",
    selectCrop: "फसल चुनें",
    describeSymptoms: "लक्षणों का वर्णन करें (वैकल्पिक)",
    describeSymptomsPlaceholder: "जैसे, पत्तियों पर छोटे भूरे धब्बे, किनारों का पीला पड़ना, सफेद फफूंद...",
    uploadLeafImage: "पत्ती की तस्वीर अपलोड करें",
    dragDropOrClick: "पत्ती की तस्वीर यहाँ खींचें या खोजने के लिए क्लिक करें",
    runningDiagnostic: "नैदानिक पर्ची तैयार की जा रही है...",
    analyzingFoliage: "पत्ती के पैटर्न का विश्लेषण और कृषि विशेषज्ञ नियमों का मिलान...",
    geminiAiAgronomist: "जेमिनी एआई कृषि वैज्ञानिक",
    offlineLocalHeuristics: "ऑफ़लाइन स्थानीय विशेषज्ञ",
    localExpertPrescription: "स्थानीय विशेषज्ञ पर्ची",
    diagnosticPrescriptionSheet: "रोग निदान और उपचार पर्ची",
    analysisConfidence: "रोग आत्मविश्वास स्कोर",
    symptoms: "देखे गए लक्षण",
    causes: "रोग और उत्पन्न होने के कारण",
    treatment: "वैज्ञानिक उपचार और प्रबंधन",
    organic: "जैविक उपचार",
    chemical: "रासायनिक उपचार",
    prevention: "दीर्घकालिक रोकथाम रणनीति",
    sampleDiseasedPhotos: "रोग अनुकरण करने के लिए एक नमूना फोटो पर क्लिक करें",

    // Chat Screen
    aiAgronomistExpertChat: "एआई कृषि विशेषज्ञ चैट",
    askFarmingQuestion: "कीट प्रबंधन, खाद की मात्रा या सिंचाई के बारे में कोई भी सवाल पूछें",
    messagePlaceholder: "पीले पत्तों, खाद की खुराक के बारे में पूछें...",
    typing: "कृषि वैज्ञानिक विश्लेषण कर रहे हैं...",

    // Market Intelligence
    marketIntelMandi: "बाज़ार की जानकारी और मंडी भाव",
    marketIntelDesc: "वास्तविक समय कृषि मूल्य सूचकांक, एपीएमसी मंडी रुझान और लाभ अनुमानक",
    liveIndex: "लाइव सूचकांक",
    syncPrices: "मंडी भाव सिंक करें",
    syncSuccessPrices: "फसल मंडी सूचकांक सिंक और कैश कर लिए गए हैं। ऑफ़लाइन गणना तैयार है।",
    commoditySelector: "वस्तु चुनें",
    mandiPriceTrends: "एपीएमसी मंडी भाव के रुझान",
    mandiName: "मंडी का नाम",
    currentPrice: "वर्तमान मूल्य (प्रति क्विंटल)",
    dailyChange: "दैनिक परिवर्तन",
    profitabilityCalc: "खेती की लागत और लाभ कैलकुलेटर",
    acresLabel: "भूमि क्षेत्र (एकड़ में)",
    expectedYieldLabel: "अपेक्षित पैदावार (क्विंटल/एकड़)",
    costPerAcreLabel: "खेती की लागत (₹/एकड़)",
    estimatedRevenue: "अनुमानित कुल राजस्व",
    netProfitMargin: "शुद्ध लाभ मार्जिन",
    netProfit: "शुद्ध लाभ",

    // About Us
    ourVisionStory: "हमारा दृष्टिकोण और कहानी",
    visionTitle: "भारतीय कृषि के भविष्य को संवारना।",
    visionDesc: "भारतीय आजीविका और पैदावार को सुरक्षित करने के लिए पारंपरिक कृषि ज्ञान को उन्नत एआई तकनीक के साथ जोड़ना।",
    originStory: "मूल कहानी",
    fromVisionToVitality: "दृष्टिकोण से जीवन शक्ति तक",
    originDesc1: "फसल डॉक्टर का जन्म हरियाणा और पंजाब के कृषि प्रधान क्षेत्रों में हुआ था। स्थानीय किसानों को अचानक मौसम की आपदाओं, कीटों के प्रकोप और बाजार के बिचौलियों से जूझते हुए देखकर, हमने एक ऐसा सहायक बनाने का फैसला किया जो सीधे उनकी जेब में समा सके।",
    originDesc2: "सटीक स्थानीय मौसम पूर्वानुमानों को सर्वर-साइड जेमिनी एआई मॉडल के साथ जोड़कर, हम क्षणों में सटीक फसल निदान और पर्ची प्रदान करते हैं, जिससे खेती से अनिश्चितता हमेशा के लिए दूर हो जाती है।",
    coreValues: "मुख्य वैज्ञानिक स्तंभ",
    value1Title: "कृषि प्रामाणिकता",
    value1Desc: "प्रत्येक रासायनिक या जैविक खाद की सलाह राज्य कृषि विश्वविद्यालयों के आंकड़ों के आधार पर वैज्ञानिक रूप से तैयार की जाती है।",
    value2Title: "डिजिटल समावेशिता",
    value2Desc: "पहुंच में आसानी के लिए कई क्षेत्रीय भाषाओं, स्पष्ट पाठ और स्थानीय आवाज संदेशों का गहरा समर्थन।",
    value3Title: "ऑफ़लाइन लचीलापन",
    value3Desc: "हमारा स्थानीय मिलान इंजन बिना हाई-स्पीड इंटरनेट के गहरे खेतों में भी उत्कृष्ट कार्य करता है।"
  },
  Punjabi: {
    // Nav & Shell
    home: "ਹੋਮ",
    diagnosis: "ਬਿਮਾਰੀ ਜਾਂਚ",
    assistant: "ਸਹਾਇਕ",
    insights: "ਮੌਸਮ",
    market: "ਮੰਡੀ ਭਾਅ",
    mission: "ਸਾਡਾ ਮਿਸ਼ਨ",
    online: "ਔਨਲਾਈਨ",
    offline: "ਔਫਲਾਈਨ",
    logout: "ਲੌਗਆਉਟ",
    backToHome: "ਹੋਮ 'ਤੇ ਵਾਪਸ ਜਾਓ",
    chooseLanguage: "ਰਾਜ ਦੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    languageSuffix: "ਭਾਸ਼ਾ",
    namaste: "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ",
    farmOverviewFor: "ਇੱਥੇ ਤੁਹਾਡੇ ਖੇਤ ਦੀ ਸਥਿਤੀ ਦਾ ਵੇਰਵਾ ਹੈ",
    offlineModeActive: "ਔਫਲਾਈਨ ਮੋਡ ਸਰਗਰਮ",
    offlineModeDesc: "ਤੁਸੀਂ ਵਰਤਮਾਨ ਵਿੱਚ ਡਿਸਕਨੈਕਟ ਹੋ ਜਾਂ ਔਫਲਾਈਨ ਮੋਡ ਦੀ ਨਕਲ ਕਰ ਰਹੇ ਹੋ। ਮਹੱਤਵਪੂਰਨ ਮੌਸਮ, ਫਸਲ ਮੈਟ੍ਰਿਕਸ ਅਤੇ ਮੰਡੀ ਸੂਚਕਾਂਕ ਲੋਕਲ ਸਟੋਰੇਜ ਕੈਸ਼ ਤੋਂ ਲੋਡ ਕੀਤੇ ਗਏ ਹਨ।",

    // Landing Page
    landingTitle: "ਪੰਜਾਬ ਅਤੇ ਭਾਰਤੀ ਖੇਤੀਬਾੜੀ ਦੇ ਭਵਿੱਖ ਨੂੰ ਸੁਧਾਰਨਾ",
    landingSubtitle: "ਕਿਸਾਨਾਂ ਦੀ ਰੋਜ਼ੀ-ਰੋਟੀ ਅਤੇ ਫਸਲ ਦੀ ਸੁਰੱਖਿਆ ਲਈ ਰਵਾਇਤੀ ਖੇਤੀ ਗਿਆਨ ਨੂੰ ਉੱਨਤ ਏਆਈ ਸ਼ੁੱਧਤਾ ਨਾਲ ਜੋੜਨਾ।",
    startFarming: "ਖੇਤੀ ਸ਼ੁਰੂ ਕਰੋ",
    features: "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    howItWorks: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",
    successStories: "ਸਫਲਤਾ ਦੀਆਂ ਕਹਾਣੀਆਂ",
    ourMission: "ਸਾਡਾ ਮਿਸ਼ਨ",
    aiCropDoctor: "ਏਆਈ ਫਸਲ ਡਾਕਟਰ",
    aiCropDoctorDesc: "ਆਪਣੇ ਫ਼ੋਨ ਦੇ ਕੈਮਰੇ ਨਾਲ ਫ਼ਸਲ ਦੀਆਂ ਬਿਮਾਰੀਆਂ ਦਾ ਤੁਰੰਤ ਪਤਾ ਲਗਾਓ ਅਤੇ ਪ੍ਰਮਾਣਿਤ ਜੈਵਿਕ ਅਤੇ ਰਸਾਇਣਕ ਇਲਾਜ ਪ੍ਰਾਪਤ ਕਰੋ।",
    hyperLocalWeather: "ਸਥਾਨਕ ਮੌਸਮ",
    hyperLocalWeatherDesc: "ਆਪਣੇ ਖੇਤਰ ਦੇ ਅਨੁਕੂਲ ਅਸਲ-ਸਮੇਂ ਦੇ ਮੌਸਮ ਮੈਟ੍ਰਿਕਸ, ਮਿੱਟੀ ਦੀ ਨਮੀ ਅਤੇ ਕੀਟਨਾਸ਼ਕ ਛਿੜਕਾਅ ਦੇ ਸਹੀ ਸਮੇਂ ਦੀ ਜਾਣਕਾਰੀ ਪ੍ਰਾਪਤ ਕਰੋ।",
    mandiPrices: "ਮੰਡੀ ਭਾਅ",
    mandiPricesDesc: "ਆਪਣੀ ਸਥਾਨਕ ਏਪੀਐਮਸੀ ਮੰਡੀਆਂ ਦੇ ਪਾਰਦਰਸ਼ੀ ਮੁੱਲ ਸੂਚਕਾਂਕ ਨਾਲ ਹਮੇਸ਼ਾ ਅੱਗੇ ਰਹੋ ਅਤੇ ਫਸਲ ਦੇ ਮੁਨਾਫੇ ਦੀ ਗਣਨਾ ਕਰੋ।",
    voiceAssist: "ਆਵਾਜ਼ ਸਹਾਇਤਾ",
    voiceAssistDesc: "ਸਵੈਚਲਿਤ ਸਪਸ਼ਟ ਆਵਾਜ਼ ਸਹਾਇਤਾ ਨਾਲ ਆਪਣੀ ਮਾਤ ਭਾਸ਼ਾ ਵਿੱਚ ਵਿਗਿਆਨਕ ਖੇਤੀ ਦੀ ਸਲਾਹ ਸੁਣੋ।",

    // Login Screen
    farmerLogin: "ਕਿਸਾਨ ਲੌਗਇਨ",
    enterPhone: "ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ",
    sendOtp: "ਓਟੀਪੀ ਭੇਜੋ",
    verifyOtp: "ਓਟੀਪੀ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
    agreeTerms: "ਜਾਰੀ ਰੱਖ ਕੇ, ਤੁਸੀਂ ਸਾਡੀਆਂ ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ ਅਤੇ ਗੋਪਨੀਯਤਾ ਨੀਤੀ ਨਾਲ ਸਹਿਮਤ ਹੁੰਦੇ ਹੋ।",
    phonePlaceholder: "10-ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ",
    otpSent: "ਤੁਹਾਡੇ ਨੰਬਰ 'ਤੇ ਓਟੀਪੀ ਭੇਜ ਦਿੱਤਾ ਗਿਆ ਹੈ",
    verifyAndLogin: "ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਲੌਗਇਨ ਕਰੋ",

    // Language Step
    onboardingChooseLanguage: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    onboardingChooseLanguageDesc: "ਵਿਅਕਤੀਗਤ ਖੇਤੀਬਾੜੀ ਸਲਾਹਕਾਰ, ਮਾਰਕੀਟ ਜਾਣਕਾਰੀ ਅਤੇ ਆਵਾਜ਼ ਮਾਰਗਦਰਸ਼ਨ ਲਈ ਆਪਣੀ ਮਾਤ ਭਾਸ਼ਾ ਦੀ ਚੋਣ ਕਰੋ।",
    detectingLocation: "ਖੇਤ ਦੇ ਸਥਾਨ ਦਾ ਪਤਾ ਲਗਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...",
    locationDetected: "ਖੇਤ ਦਾ ਸਥਾਨ ਸਫਲਤਾਪੂਰਵਕ ਮਿਲ ਗਿਆ ਹੈ",
    nextStep: "ਅਗਲਾ ਕਦਮ",

    // Crop Step
    whatAreYouGrowing: "ਤੁਸੀਂ ਕੀ ਉਗਾ ਰਹੇ ਹੋ?",
    selectCropsDesc: "ਆਪਣੀ ਫਸਲ ਦੀ ਬਿਮਾਰੀ ਜਾਂਚ, ਮੌਸਮ ਸੂਚਕਾਂਕ ਅਤੇ ਮੰਡੀ ਦੇ ਰੁਝਾਨਾਂ ਨੂੰ ਅਨੁਕੂਲ ਕਰਨ ਲਈ ਆਪਣੀ ਮੌਜੂਦਾ ਖੇਤੀ ਦੀ ਚੋਣ ਕਰੋ।",
    back: "ਪਿੱਛੇ",

    // Profile Step
    completeProfile: "ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ ਪੂਰਾ ਕਰੋ",
    enterName: "ਆਪਣਾ ਨਾਮ ਦਰਜ ਕਰੋ",
    enterNamePlaceholder: "ਜਿਵੇਂ, ਰਮੇਸ਼ ਕੁਮਾਰ",
    voiceGuided: "ਆਵਾਜ਼-ਨਿਰਦੇਸ਼ਿਤ ਸਹਾਇਤਾ",
    voiceGuidedDesc: "ਮੇਰੀ ਖੇਤਰੀ ਭਾਸ਼ਾ ਵਿੱਚ ਨੁਸਖ਼ੇ ਅਤੇ ਮੌਸਮ ਦੀਆਂ ਚੇਤਾਵਨੀਆਂ ਆਪਣੇ ਆਪ ਪੜ੍ਹ ਕੇ ਸੁਣਾਓ",
    submitEnterFarm: "ਜਮ੍ਹਾਂ ਕਰੋ ਅਤੇ ਖੇਤ ਵਿੱਚ ਪ੍ਰਵੇਸ਼ ਕਰੋ",

    // Dashboard
    liveFarmClimate: "ਖੇਤ ਦਾ ਮੌਸਮ",
    overcastClouds: "ਬੱਦਲਵਾਈ",
    humidity: "ਨਮੀ",
    wind: "ਹਵਾ",
    uvIndex: "ਯੂਵੀ ਇੰਡੈਕਸ",
    spraySuitability: "ਛਿੜਕਾਅ ਦੀ ਯੋਗਤਾ",
    highIdeal: "ਬਹੁਤ ਵਧੀਆ / ਢੁਕਵਾਂ",
    sprayAdvisoryText: "ਹਵਾ ਦੀ ਗਤੀ ਹੌਲੀ (8 ਕਿਲੋਮੀਟਰ/ਘੰਟਾ) ਹੈ ਅਤੇ ਤਾਪਮਾਨ 35 ਡਿਗਰੀ ਸੈਲਸੀਅਸ ਤੋਂ ਘੱਟ ਹੈ। ਨਮੀ ਅਨੁਕੂਲ ਹੈ। ਫੋਲੀਅਰ ਪੌਸ਼ਟਿਕ ਤੱਤ ਜਾਂ ਬਾਇਓ-ਫੰਗੀਸਾਈਡ ਦੇ ਛਿੜਕਾਅ ਦਾ ਸਹੀ ਸਮਾਂ ਹੈ!",
    targetHours: "ਸਹੀ ਸਮਾਂ",
    cropHealthStatus: "ਮੁੱਖ ਫਸਲ ਦੀ ਸਿਹਤ ਸਥਿਤੀ",
    diagnoseLeaf: "ਪੱਤੇ ਦੀ ਜਾਂਚ ਕਰੋ",
    consultExpert: "ਮਾਹਿਰ ਦੀ ਸਲਾਹ",
    status: "ਸਥਿਤੀ",
    yield: "ਝਾੜ",
    estimatedValue: "ਅਨੁਮਾਨਿਤ ਮੁੱਲ",
    riskIndex: "ਜੋਖਮ ਸੂਚਕਾਂਕ",
    healthy: "ਤੰਦਰੁਸਤ",
    yellowLeafWarn: "ਪੀਲੇ ਪੱਤਿਆਂ ਦੀ ਚੇਤਾਵਨੀ",
    lowRisk: "ਘੱਟ ਜੋਖਮ",
    mediumRisk: "ਦਰਮਿਆਨਾ ਜੋਖਮ",
    highRisk: "ਉੱਚ ਜੋਖਮ",
    cropAdvisoryPrescription: "ਫਸਲ ਸਲਾਹ ਅਤੇ ਪਰਚੀ",
    advisoryAlert: "48 ਘੰਟਿਆਂ ਵਿੱਚ ਭਾਰੀ ਮੀਂਹ ਦੀ ਭਵਿੱਖਬਾਣੀ। ਖਾਦ ਦੇ ਵਹਿਣ ਤੋਂ ਬਚਣ ਲਈ ਯੂਰੀਆ ਪਾਉਣਾ ਮੁਲਤਵੀ ਕਰੋ।",
    todayAction: "ਅੱਜ ਦੀ ਕਾਰਜ ਯੋਜਨਾ",
    advisoryAction1: "ਝੋਨੇ ਦੇ ਫੁਟਾਰੇ ਸਮੇਂ 2-3 ਇੰਚ ਪਾਣੀ ਖੜ੍ਹਾ ਰੱਖਣਾ ਯਕੀਨੀ ਬਣਾਓ।",
    advisoryAction2: "ਬਿਮਾਰੀ ਜਾਂ ਪੱਤਿਆਂ ਦੇ ਧੱਬਿਆਂ ਦੇ ਸ਼ੁਰੂਆਤੀ ਲੱਛਣਾਂ ਲਈ ਫਸਲ ਦੇ ਹੇਠਲੇ ਹਿੱਸੇ ਦੀ ਜਾਂਚ ਕਰੋ।",
    activeCropTrack: "ਸਰਗਰਮ ਫਸਲ ਵਿਸ਼ਲੇਸ਼ਣ",
    cultivatedCrop: "ਖੇਤੀ ਕੀਤੀ ਫਸਲ",
    yieldPrediction: "ਅਨੁਮਾਨਿਤ ਝਾੜ",
    estimatedMarketValue: "ਅਨੁਮਾਨਿਤ ਮੁੱਲ",
    checkMandiRates: "ਮੰਡੀ ਭਾਅ ਦੇਖੋ",
    optimalIrrigation: "ਅਨੁਕੂਲ ਸਿੰਚਾਈ",
    irrigationAdvisoryText: "ਮਿੱਟੀ ਦੀ ਨਮੀ ਹੁਣ 32% ਹੈ। ਅਗਲੇ 48 ਘੰਟਿਆਂ ਤੱਕ ਸਿੰਚਾਈ ਦੀ ਕੋਈ ਲੋੜ ਨਹੀਂ ਹੈ। ਸ਼ੁੱਕਰਵਾਰ ਨੂੰ ਮੀਂਹ ਪੈਣ ਦੀ ਸੰਭਾਵਨਾ ਹੈ।",
    viewMoistureChart: "ਨਮੀ ਚਾਰਟ ਦੇਖੋ",
    nitrogenUreaLevel: "ਨਾਈਟ੍ਰੋਜਨ ਅਤੇ ਯੂਰੀਆ ਦਾ ਪੱਧਰ",
    nitrogenAdvisoryText: "ਕਲੋਰੋਫਿਲ ਦਾ ਪੱਧਰ ਸਧਾਰਣ ਹੈ। ਚੌਥੇ ਹਫਤੇ ਵਿੱਚ ਪ੍ਰਤੀ ਏਕੜ 20 ਕਿੱਲੋ ਯੂਰੀਆ ਪਾਉਣ ਦੀ ਸਲਾਹ ਦਿੱਤੀ ਜਾਂਦੀ ਹੈ।",
    askCropAssistant: "ਫਸਲ ਸਹਾਇਕ ਤੋਂ ਪੁੱਛੋ",
    outbreakPestForecast: "ਕੀਟ ਦੇ ਹਮਲੇ ਦੀ ਚੇਤਾਵਨੀ",
    regionalStemBorerWarning: "ਤਣਾ ਛੇਦਕ ਕੀੜੇ ਦੀ ਖੇਤਰੀ ਚੇਤਾਵਨੀ",
    stemBorerAdvisoryText: "ਉੱਚ ਨਮੀ ਕੀਟ ਦੇ ਹਮਲੇ ਲਈ ਅਨੁਕੂਲ ਵਾਤਾਵਰਣ ਬਣਾਉਂਦੀ ਹੈ। ਹਮਲੇ ਦਾ ਜੋਖਮ: ",
    initiateAiLeafScan: "ਹੁਣੇ ਏਆਈ ਪੱਤਾ ਸਕੈਨ ਸ਼ੁਰੂ ਕਰੋ",
    smartFarmTodos: "ਖੇਤ ਦੇ ਮਹੱਤਵਪੂਰਨ ਕੰਮ",
    scanWestLeafZone: "ਪੱਛਮੀ ਖੇਤਰ ਦੇ ਪੱਤਿਆਂ ਨੂੰ ਸਕੈਨ ਕਰੋ",
    pendingScan: "ਸਕੈਨ ਬਾਕੀ ਹੈ",
    scanButton: "ਸਕੈਨ",
    addUreaTopdress: "20 ਕਿੱਲੋ ਯੂਰੀਆ ਪਾਓ",
    sowingWeek4: "ਬੁਆਈ ਦਾ ਚੌਥਾ ਹਫ਼ਤਾ",
    week4Label: "ਚੌਥਾ ਹਫ਼ਤਾ",
    dailyUpdate: "ਰੋਜ਼ਾਨਾ ਅਪਡੇਟ",
    whatToPlantNext: "ਅੱਗੇ ਕੀ ਬੀਜੀਏ?",
    durumWheat: "ਕਣਕ ਦੀ ਉੱਨਤ ਕਿਸਮ",
    optimalSowing: "ਬੁਆਈ ਦਾ ਸਹੀ ਸਮਾਂ:",
    novemberRabi: "ਨਵੰਬਰ (ਰਬੀ ਸੀਜ਼ਨ)",
    estimatedDemand: "ਅਨੁਮਾਨਿਤ ਮੰਗ:",
    veryHigh: "ਬਹੁਤ ਉੱਚੀ (+12%)",
    durumWheatAdvisoryText: "ਵਿਸ਼ਵ ਪੱਧਰ 'ਤੇ ਘੱਟ ਸਟਾਕ ਕਾਰਨ, ਕਣਕ ਦੀ ਉੱਨਤ ਕਿਸਮ ਮੰਡੀਆਂ ਵਿੱਚ ਐਮਐਸਪੀ ਤੋਂ 15% ਵੱਧ ਭਾਅ 'ਤੇ ਵਿਕਣ ਦੀ ਉਮੀਦ ਹੈ। ਸਿਫਾਰਸ਼ੀ ਕਿਸਮ: HD 3086.",

    // Weather Insights
    weatherSoilInsights: "ਮੌਸਮ ਅਤੇ ਮਿੱਟੀ ਦੀ ਜਾਣਕਾਰੀ",
    weatherSoilDesc: "ਸਥਾਨਕ ਮੌਸਮ ਸਲਾਹ, ਮਿੱਟੀ ਦੀ ਨਮੀ ਅਤੇ ਤਾਪਮਾਨ ਅਤੇ ਪੂਰਵ-ਅਨੁਮਾਨ",
    liveSynced: "ਲਾਈਵ ਸਿੰਕ ਕੀਤਾ ਗਿਆ",
    offlineCache: "ਔਫਲਾਈਨ ਡੇਟਾ ਦੇਖਿਆ ਜਾ ਰਿਹਾ ਹੈ",
    syncWeather: "ਮੌਸਮ ਅਪਡੇਟ ਕਰੋ",
    syncing: "ਅਪਡੇਟ ਹੋ ਰਿਹਾ ਹੈ...",
    syncSuccessWeather: "ਫਸਲ ਡਾਟਾਬੇਸ ਅਪਡੇਟ ਕੀਤਾ ਗਿਆ। ਮੌਸਮ ਦੀ ਸਲਾਹ ਅਤੇ ਮਿੱਟੀ ਦੀ ਨਮੀ ਨੂੰ ਤੁਹਾਡੇ ਲੋਕਲ ਕੈਸ਼ ਵਿੱਚ ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਕਰ ਲਿਆ ਗਿਆ ਹੈ।",
    rainAdvisory: "ਸਮਾਰਟ ਮੀਂਹ ਦੀ ਚੇਤਾਵਨੀ",
    heavyRainAlert: "2 ਦਿਨਾਂ ਵਿੱਚ ਭਾਰੀ ਮੀਂਹ (78 ਮਿਲੀਮੀਟਰ) ਦੀ ਚੇਤਾਵਨੀ। ਸਿੰਚਾਈ ਚੈਨਲਾਂ ਨੂੰ ਤੁਰੰਤ ਸੁਰੱਖਿਅਤ ਕਰੋ।",
    soilTelemetry: "ਮਿੱਟੀ ਦੀ ਸਥਿਤੀ",
    soilMoisture: "ਮਿੱਟੀ ਦੀ ਨਮੀ",
    soilTemp: "ਮਿੱਟੀ ਦਾ ਤਾਪਮਾਨ",
    statusFavorable: "ਸਥਿਤੀ: ਅਨੁਕੂਲ",
    idealForTillering: "ਫੁਟਾਰੇ ਲਈ ਆਦਰਸ਼",
    sevenDayForecast: "7-ਦਿਨਾਂ ਦਾ ਮੌਸਮ ਅਤੇ ਛਿੜਕਾਅ ਯੋਗਤਾ ਪੂਰਵ-ਅਨੁਮਾਨ",
    day: "ਦਿਨ",
    temp: "ਤਾਪਮਾਨ",
    condition: "ਮੌਸਮ",
    rainProb: "ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ",
    windSpeed: "ਹਵਾ ਦੀ ਗਤੀ",

    // Diagnosis Screen
    aiCropScanner: "ਏਆਈ ਫਸਲ ਰੋਗ ਸਕੈਨਰ",
    aiCropScannerDesc: "ਬਿਮਾਰ ਪੌਦੇ ਦੇ ਪੱਤਿਆਂ ਦੀ ਫੋਟੋ ਖਿੱਚੋ ਜਾਂ ਅਪਲੋਡ ਕਰੋ। ਸਾਡੀ ਜੈਮਿਨੀ ਏਆਈ ਤੁਰੰਤ ਰੋਗ ਦਾ ਪਤਾ ਲਗਾ ਕੇ ਨੁਸਖ਼ਾ ਤਿਆਰ ਕਰਦੀ ਹੈ।",
    offlineModelEngaged: "ਔਫਲਾਈਨ ਮਾਹਿਰ ਮਾਡਲ ਸਰਗਰਮ",
    selectCrop: "ਫਸਲ ਚੁਣੋ",
    describeSymptoms: "ਲੱਛਣਾਂ ਦਾ ਵਰਣਨ ਕਰੋ (ਵੈਕਲਪਿਕ)",
    describeSymptomsPlaceholder: "ਜਿਵੇਂ, ਪੱਤਿਆਂ 'ਤੇ ਛੋਟੇ ਭੂਰੇ ਧੱਬੇ, ਕਿਨਾਰਿਆਂ ਦਾ ਪੀਲਾ ਹੋਣਾ, ਚਿੱਟੀ ਉੱਲੀ...",
    uploadLeafImage: "ਪੱਤੇ ਦੀ ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ",
    dragDropOrClick: "ਪੱਤੇ ਦੀ ਫੋਟੋ ਇੱਥੇ ਖਿੱਚੋ ਜਾਂ ਲੱਭਣ ਲਈ ਕਲਿੱਕ ਕਰੋ",
    runningDiagnostic: "ਜਾਂਚ ਚੱਲ ਰਹੀ ਹੈ...",
    analyzingFoliage: "ਪੱਤਿਆਂ ਦੇ ਪੈਟਰਨ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਅਤੇ ਖੇਤੀ ਮਾਹਿਰਾਂ ਦੇ ਨਿਯਮਾਂ ਦਾ ਮਿਲਾਨ...",
    geminiAiAgronomist: "ਜੈਮਿਨੀ ਏਆਈ ਖੇਤੀ ਮਾਹਿਰ",
    offlineLocalHeuristics: "ਔਫਲਾਈਨ ਸਥਾਨਕ ਮਾਹਿਰ",
    localExpertPrescription: "ਸਥਾਨਕ ਮਾਹਿਰ ਪਰਚੀ",
    diagnosticPrescriptionSheet: "ਰੋਗ ਜਾਂਚ ਅਤੇ ਇਲਾਜ ਪਰਚੀ",
    analysisConfidence: "ਬਿਮਾਰੀ ਜਾਂਚ ਸਕੋਰ",
    symptoms: "ਦੇਖੇ ਗਏ ਲੱਛਣ",
    causes: "ਰੋਗ ਦੇ ਕਾਰਨ",
    treatment: "ਵਿਗਿਆਨਕ ਇਲਾਜ ਅਤੇ ਪ੍ਰਬੰਧਨ",
    organic: "ਜੈਵਿਕ ਇਲਾਜ",
    chemical: "ਰਸਾਇਣਕ ਇਲਾਜ",
    prevention: "ਲੰਬੇ ਸਮੇਂ ਦੀ ਰੋਕਥਾਮ ਰਣਨੀਤੀ",
    sampleDiseasedPhotos: "ਬਿਮਾਰੀ ਦੀ ਨਕਲ ਕਰਨ ਲਈ ਇੱਕ ਨਮੂਨਾ ਫੋਟੋ 'ਤੇ ਕਲਿੱਕ ਕਰੋ",

    // Chat Screen
    aiAgronomistExpertChat: "ਏਆਈ ਖੇਤੀ ਮਾਹਿਰ ਨਾਲ ਗੱਲਬਾਤ",
    askFarmingQuestion: "ਕੀੜੇ-ਮਕੌੜਿਆਂ ਦੀ ਰੋਕਥਾਮ, ਖਾਦਾਂ ਦੀ ਵਰਤੋਂ ਜਾਂ ਸਿੰਚਾਈ ਬਾਰੇ ਕੋਈ ਵੀ ਸਵਾਲ ਪੁੱਛੋ",
    messagePlaceholder: "ਪੀਲੇ ਪੱਤਿਆਂ, ਖਾਦਾਂ ਦੀ ਮਾਤਰਾ ਬਾਰੇ ਪੁੱਛੋ...",
    typing: "ਖੇਤੀ ਮਾਹਿਰ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰ ਰਹੇ ਹਨ...",

    // Market Intelligence
    marketIntelMandi: "ਮੰਡੀ ਜਾਣਕਾਰੀ ਅਤੇ ਭਾਅ",
    marketIntelDesc: "ਅਸਲ-ਸਮੇਂ ਦੇ ਮੰਡੀ ਭਾਅ, ਸਰਕਾਰੀ ਰੁਝਾਨ ਅਤੇ ਮੁਨਾਫੇ ਦੀ ਗਣਨਾ",
    liveIndex: "ਲਾਈਵ ਸੂਚਕਾਂਕ",
    syncPrices: "ਭਾਅ ਸਿੰਕ ਕਰੋ",
    syncSuccessPrices: "ਮੰਡੀ ਭਾਅ ਸਿੰਕ ਅਤੇ ਸੁਰੱਖਿਅਤ ਕਰ ਲਏ ਗਏ ਹਨ। ਔਫਲਾਈਨ ਗਣਨਾ ਤਿਆਰ ਹੈ।",
    commoditySelector: "ਫਸਲ ਚੁਣੋ",
    mandiPriceTrends: "ਏਪੀਐਮਸੀ ਮੰਡੀ ਦੇ ਭਾਅ",
    mandiName: "ਮੰਡੀ ਦਾ ਨਾਮ",
    currentPrice: "ਮੌਜੂਦਾ ਭਾਅ (ਪ੍ਰਤੀ ਕੁਇੰਟਲ)",
    dailyChange: "ਰੋਜ਼ਾਨਾ ਤਬਦੀਲੀ",
    profitabilityCalc: "ਲਾਗਤ ਅਤੇ ਮੁਨਾਫ਼ਾ ਕੈਲਕੁਲੇਟਰ",
    acresLabel: "ਜ਼ਮੀਨ ਦਾ ਰਕਬਾ (ਏਕੜ ਵਿੱਚ)",
    expectedYieldLabel: "ਅਨੁਮਾਨਿਤ ਝਾੜ (ਕੁਇੰਟਲ/ਏਕੜ)",
    costPerAcreLabel: "ਖੇਤੀ ਦੀ ਲਾਗਤ (₹/ਏਕੜ)",
    estimatedRevenue: "ਅਨੁਮਾਨਿਤ ਕੁੱਲ ਆਮਦਨ",
    netProfitMargin: "ਸ਼ੁੱਧ ਮੁਨਾਫ਼ਾ ਫੀਸਦੀ",
    netProfit: "ਸ਼ੁੱਧ ਮੁਨਾਫ਼ਾ",

    // About Us
    ourVisionStory: "ਸਾਡਾ ਦ੍ਰਿਸ਼ਟੀਕੋਣ ਅਤੇ ਕਹਾਣੀ",
    visionTitle: "ਪੰਜਾਬ ਅਤੇ ਭਾਰਤੀ ਖੇਤੀਬਾੜੀ ਦੇ ਭਵਿੱਖ ਨੂੰ ਸੰਵਾਰਨਾ।",
    visionDesc: "ਕਿਸਾਨਾਂ ਦੀ ਰੋਜ਼ੀ-ਰੋਟੀ ਅਤੇ ਫਸਲਾਂ ਦੀ ਸੁਰੱਖਿਆ ਲਈ ਰਵਾਇਤੀ ਖੇਤੀ ਗਿਆਨ ਨੂੰ ਉੱਨਤ ਏਆਈ ਤਕਨੀਕ ਨਾਲ ਜੋੜਨਾ।",
    originStory: "ਮੂਲ ਕਹਾਣੀ",
    fromVisionToVitality: "ਦ੍ਰਿਸ਼ਟੀਕੋਣ ਤੋਂ ਜੀਵਨ ਸ਼ਕਤੀ ਤੱਕ",
    originDesc1: "ਫਸਲ ਡਾਕਟਰ ਦਾ ਜਨਮ ਪੰਜਾਬ ਅਤੇ ਹਰਿਆਣਾ ਦੇ ਖੇਤੀਬਾੜੀ ਖੇਤਰਾਂ ਵਿੱਚ ਹੋਇਆ ਸੀ। ਸਥਾਨਕ ਕਿਸਾਨਾਂ ਨੂੰ ਅਚਾਨਕ ਮੌਸਮੀ ਆਫ਼ਤਾਂ, ਕੀੜਿਆਂ ਦੇ ਹਮਲੇ ਅਤੇ ਮੰਡੀ ਦੇ ਵਿਚੋਲਿਆਂ ਨਾਲ ਜੂਝਦੇ ਹੋਏ ਦੇਖ ਕੇ, ਅਸੀਂ ਇੱਕ ਅਜਿਹਾ ਸਹਾਇਕ ਬਣਾਉਣ ਦਾ ਫੈਸਲਾ ਕੀਤਾ ਜੋ ਸਿੱਧਾ ਉਹਨਾਂ ਦੀ ਜੇਬ ਵਿੱਚ ਆ ਸਕੇ।",
    originDesc2: "ਸਟੀਕ ਸਥਾਨਕ ਮੌਸਮ ਦੀ ਭਵਿੱਖਬਾਣੀ ਨੂੰ ਸਰਵਰ-ਸਾਈਡ ਜੈਮਿਨੀ ਏਆਈ ਮਾਡਲਾਂ ਨਾਲ ਜੋੜ ਕੇ, ਅਸੀਂ ਕੁਝ ਪਲਾਂ ਵਿੱਚ ਸਹੀ ਫਸਲ ਦੀ ਬਿਮਾਰੀ ਜਾਂਚ ਅਤੇ ਇਲਾਜ ਪ੍ਰਦਾਨ ਕਰਦੇ ਹਾਂ।",
    coreValues: "ਮੁੱਖ ਵਿਗਿਆਨਕ ਸਿਧਾਂਤ",
    value1Title: "ਖੇਤੀਬਾੜੀ ਦੀ ਪ੍ਰਮਾਣਿਕਤਾ",
    value1Desc: "ਹਰ ਰਸਾਇਣਕ ਜਾਂ ਜੈਵਿਕ ਖਾਦ ਦੀ ਸਲਾਹ ਸਰਕਾਰੀ ਖੇਤੀਬਾੜੀ ਯੂਨੀਵਰਸਿਟੀਆਂ ਦੇ ਅੰਕੜਿਆਂ ਦੇ ਅਧਾਰ 'ਤੇ ਤਿਆਰ ਕੀਤੀ ਜਾਂਦੀ ਹੈ।",
    value2Title: "ਡਿਜੀਟਲ ਸ਼ਮੂਲੀਅਤ",
    value2Desc: "ਆਸਾਨ ਪਹੁੰਚ ਲਈ ਕਈ ਖੇਤਰੀ ਭਾਸ਼ਾਵਾਂ, ਸਪਸ਼ਟ ਲਿਖਤ ਅਤੇ ਸਥਾਨਕ ਆਵਾਜ਼ ਸੰਦੇਸ਼ਾਂ ਦਾ ਸਮਰਥਨ।",
    value3Title: "ਔਫਲਾਈਨ ਮਜ਼ਬੂਤੀ",
    value3Desc: "ਸਾਡਾ ਸਥਾਨਕ ਮਿਲਾਨ ਇੰਜਣ ਬਿਨਾਂ ਹਾਈ-स्पीड ਇੰਟਰਨੈਟ ਦੇ ਡੂੰਘੇ ਖੇਤਾਂ ਵਿੱਚ ਵੀ ਸ਼ਾਨਦਾਰ ਕੰਮ ਕਰਦਾ ਹੈ।"
  },
  Marathi: {
    // Nav & Shell
    home: "होम",
    diagnosis: "रोग निदान",
    assistant: "मदतनीस",
    insights: "हवामान",
    market: "बाजार भाव",
    mission: "ध्येय",
    online: "ऑनलाइन",
    offline: "ऑफलाइन",
    logout: "लॉगआउट",
    backToHome: "होमवर परत जा",
    chooseLanguage: "राज्याची भाषा निवडा",
    languageSuffix: "भाषा",
    namaste: "नमस्कार",
    farmOverviewFor: "येथे तुमच्या शेतीची सद्यस्थिती आहे",
    offlineModeActive: "ऑफलाइन मोड सक्रिय",
    offlineModeDesc: "तुम्ही सध्या ऑफलाइन आहात। हवामान, पिकांची माहिती आणि बाजार भाव स्थानिक स्टोरेजमधून दाखवले जात आहेत।",

    // Landing Page
    landingTitle: "महाराष्ट्राच्या आणि भारतीय शेतीच्या भविष्याची जपणूक",
    landingSubtitle: "शेतकऱ्यांचे जीवनमान आणि पिकांच्या सुरक्षेसाठी पारंपरिक कृषी ज्ञानाला प्रगत एआय तंत्रज्ञानाची जोड।",
    startFarming: "शेती सुरू करा",
    features: "वैशिष्ट्ये",
    howItWorks: "हे कसे कार्य करते",
    successStories: "यशस्वी कथा",
    ourMission: "आमचे ध्येय",
    aiCropDoctor: "एआय क्रॉप डॉक्टर",
    aiCropDoctorDesc: "तुमच्या फोन कॅमेऱ्याने पिकांवरील रोगांचे त्वरित निदान करा आणि प्रमाणित सेंद्रिय आणि रासायनिक औषधोपचार मिळवा।",
    hyperLocalWeather: "स्थानिक हवामान",
    hyperLocalWeatherDesc: "तुमच्या परिसरातील सूक्ष्म हवामान, मातीतील ओलावा आणि कीटकनाशक फवारणीसाठी योग्य वेळेची अचूक माहिती मिळवा।",
    mandiPrices: "बाजार भाव",
    mandiPricesDesc: "तुमच्या स्थानिक कृषी उत्पन्न बाजार समित्यांचे पारदर्शक बाजार भाव जाणून घ्या आणि नफ्याची गणना करा।",
    voiceAssist: "आवाज साहाय्य",
    voiceAssistDesc: "स्वयंचलित स्पष्ट आवाज साहाय्यासह तुमच्या मातृभाषेत वैज्ञानिक शेतीचा सल्ला ऐका।",

    // Login Screen
    farmerLogin: "शेतकरी लॉगिन",
    enterPhone: "तुमचा मोबाईल नंबर टाका",
    sendOtp: "ओटीपी पाठवा",
    verifyOtp: "ओटीपीची पडताळणी करा",
    agreeTerms: "पुढे जाऊन, तुम्ही आमच्या सेवा अटी आणि गोपनीयता धोरणाशी सहमत आहात।",
    phonePlaceholder: "१० अंकी मोबाईल नंबर टाका",
    otpSent: "तुमच्या नंबरवर ओटीपी पाठवला गेला आहे",
    verifyAndLogin: "पडताळणी करा आणि लॉगिन करा",

    // Language Step
    onboardingChooseLanguage: "तुमची भाषा निवडा",
    onboardingChooseLanguageDesc: "वैयक्तिकृत कृषी सल्लागार, बाजार भाव आणि आवाज मार्गदर्शनासाठी तुमची मातृभाषा निवडा।",
    detectingLocation: "शेतीचे स्थान शोधत आहे...",
    locationDetected: "शेतीचे स्थान यशस्वीरित्या सापडले",
    nextStep: "पुढील पाऊल",

    // Crop Step
    whatAreYouGrowing: "तुम्ही काय पिकवत आहात?",
    selectCropsDesc: "तुमचे पीक रोग निदान, हवामान अंदाज आणि बाजार भाव तुमच्या पिकानुसार अनुकूल करण्यासाठी पिके निवडा।",
    back: "मागे",

    // Profile Step
    completeProfile: "शेतकरी माहिती पूर्ण करा",
    enterName: "तुमचे नाव टाका",
    enterNamePlaceholder: "उदा. रमेश कुमार",
    voiceGuided: "आवाज मार्गदर्शित साहाय्य",
    voiceGuidedDesc: "माझ्या प्रादेशिक भाषेत रोग निदान आणि हवामानाच्या सूचना स्वयंचलितपणे वाचून दाखवा",
    submitEnterFarm: "जतन करा आणि प्रवेश करा",

    // Dashboard
    liveFarmClimate: "थेट शेती हवामान",
    overcastClouds: "ढगाळ हवामान",
    humidity: "आर्द्रता",
    wind: "वारा",
    uvIndex: "यूव्ही इंडेक्स",
    spraySuitability: "फवारणीसाठी अनुकूलता",
    highIdeal: "उत्कृष्ट / योग्य",
    sprayAdvisoryText: "वाऱ्याचा वेग कमी (८ किमी/तास) आहे आणि तापमान ३५ डिग्री सेल्सियसपेक्षा कमी आहे। आर्द्रता योग्य आहे। फवारणीसाठी उत्तम वेळ आहे!",
    targetHours: "योग्य वेळ",
    cropHealthStatus: "मुख्य पीक आरोग्य स्थिती",
    diagnoseLeaf: "पानाचे निदान करा",
    consultExpert: "तज्ञांचा सल्ला",
    status: "स्थिती",
    yield: "उत्पादन",
    estimatedValue: "अंदाजे मूल्य",
    riskIndex: "जोखमीचा दर",
    healthy: "निरोगी",
    yellowLeafWarn: "पिवळ्या पानांची चेतावणी",
    lowRisk: "कमी जोखीम",
    mediumRisk: "मध्यम जोखीम",
    highRisk: "उच्च जोखीम",
    cropAdvisoryPrescription: "पीक सल्ला आणि उपाय",
    advisoryAlert: "४८ तासांत मुसळधार पावसाची शक्यता। खत वाहून जाणे टाळण्यासाठी युरिया टाकणे पुढे ढकला।",
    todayAction: "आजचे नियोजन",
    advisoryAction1: "भाताच्या पिकासाठी २-३ इंच पाणी शेतात साठवून ठेवणे सुनिश्चित करा।",
    advisoryAction2: "करपा किंवा पानांवरील ठिपके यांसारख्या रोगांच्या सुरुवातीच्या लक्षणांसाठी पिकांची तपासणी करा।",
    activeCropTrack: "सक्रिय पीक विश्लेषण",
    cultivatedCrop: "पिकवलेले पीक",
    yieldPrediction: "अंदाजे उत्पादन",
    estimatedMarketValue: "अंदाजे बाजार भाव",
    checkMandiRates: "बाजार भाव पहा",
    optimalIrrigation: "अनुकूल सिंचन",
    irrigationAdvisoryText: "मातीतील ओलावा सध्या ३२% आहे। पुढील ४८ तास सिंचनाची गरज नाही। शुक्रवारी पावसाची शक्यता आहे।",
    viewMoistureChart: "ओलावा चार्ट पहा",
    nitrogenUreaLevel: "नायट्रोजन आणि युरिया पातळी",
    nitrogenAdvisoryText: "क्लोरोफिल पातळी योग्य आहे। चौथ्या आठवड्यात प्रति एकर २० किलो युरिया फवारण्याचा सल्ला दिला जातो।",
    askCropAssistant: "मदतनीसाला विचारा",
    outbreakPestForecast: "कीड प्रादुर्भाव अंदाज",
    regionalStemBorerWarning: "खोडकिडा प्रादुर्भावाची प्रादेशिक चेतावणी",
    stemBorerAdvisoryText: "दमट हवामानामुळे खोडकिडा वाढण्याची शक्यता आहे। प्रादुर्भावाची जोखीम: ",
    initiateAiLeafScan: "आता एआय पान स्कॅनिंग सुरू करा",
    smartFarmTodos: "शेतातील महत्त्वाची कामे",
    scanWestLeafZone: "पश्चिम भागातील पानांची तपासणी करा",
    pendingScan: "तपासणी बाकी आहे",
    scanButton: "तपासा",
    addUreaTopdress: "२० किलो युरिया टाका",
    sowingWeek4: "पेरणीचा चौथा आठवडा",
    week4Label: "चौथा आठवडा",
    dailyUpdate: "दैनिक अपडेट",
    whatToPlantNext: "पुढे काय पेरावे?",
    durumWheat: "गव्हाचे प्रगत वाण",
    optimalSowing: "पेरणीची योग्य वेळ:",
    novemberRabi: "नोव्हेंबर (रब्बी हंगाम)",
    estimatedDemand: "अंदाजे मागणी:",
    veryHigh: "खूप जास्त (+12%)",
    durumWheatAdvisoryText: "जागतिक पातळीवर साठा कमी असल्याने, गव्हाच्या चांगल्या वाणांना बाजार समित्यांमध्ये चांगला भाव मिळण्याची अपेक्षा आहे। शिफारस केलेले वाण: एचडी ३०८६।",

    // Weather Insights
    weatherSoilInsights: "हवामान आणि मातीची माहिती",
    weatherSoilDesc: "स्थानिक हवामान सल्ला, मातीतील ओलावा, तापमान आणि अंदाज",
    liveSynced: "थेट अपडेट केलेले",
    offlineCache: "ऑफलाइन डेटा पाहत आहात",
    syncWeather: "हवामान अपडेट करा",
    syncing: "अपडेट होत आहे...",
    syncSuccessWeather: "कृषी डेटाबेस यशस्वीरित्या अपडेट करण्यात आला आहे आणि ऑफलाइन वापरासाठी सुरक्षित केला आहे।",
    rainAdvisory: "स्मार्ट पाऊस चेतावणी",
    heavyRainAlert: "२ दिवसांत मुसळधार पावसाचा इशारा। पाणी वाहून जाण्याचे मार्ग त्वरित मोकळे करा।",
    soilTelemetry: "मातीची सद्यस्थिती",
    soilMoisture: "मातीतील ओलावा",
    soilTemp: "मातीचे तापमान",
    statusFavorable: "स्थिती: अनुकूल",
    idealForTillering: "पीक वाढीसाठी उत्तम",
    sevenDayForecast: "७ दिवसांचा हवामान आणि फवारणी अंदाज",
    day: "दिवस",
    temp: "तापमान",
    condition: "हवामान",
    rainProb: "पावसाची शक्यता",
    windSpeed: "वाऱ्याचा वेग",

    // Diagnosis Screen
    aiCropScanner: "एआई पीक रोग स्कॅनर",
    aiCropScannerDesc: "बीमार झाडाच्या पानांचा फोटो काढा किंवा अपलोड करा। आमचे जेमिनी एआय त्वरित रोगाचे निदान करून उपचार सुचवते।",
    offlineModelEngaged: "ऑफलाइन तज्ञ मॉडेल सक्रिय",
    selectCrop: "पीक निवडा",
    describeSymptoms: "लक्षणांचे वर्णन करा (पर्यायी)",
    describeSymptomsPlaceholder: "उदा। पानांवर लहान तपकिरी ठिपके, कडा पिवळ्या पडणे, पांढरी बुरशी...",
    uploadLeafImage: "पानाचा फोटो अपलोड करा",
    dragDropOrClick: "पानाचा फोटो येथे ड्रॅग करा किंवा निवडण्यासाठी क्लिक करा",
    runningDiagnostic: "रोग निदान सुरू आहे...",
    analyzingFoliage: "पानावरील पॅटर्नचे विश्लेषण आणि कृषी तज्ञांच्या नियमांचे मिलान...",
    geminiAiAgronomist: "जेमिनी एआई कृषी वैज्ञानिक",
    offlineLocalHeuristics: "ऑफलाइन स्थानिक तज्ञ",
    localExpertPrescription: "स्थानिक तज्ञ पर्ची",
    diagnosticPrescriptionSheet: "रोग निदान आणि उपचार पर्ची",
    analysisConfidence: "रोग निदान अचूकता स्कोर",
    symptoms: "आढळलेली लक्षणे",
    causes: "रोगाची कारणे",
    treatment: "वैज्ञानिक उपचार आणि व्यवस्थापन",
    organic: "सेंद्रिय उपचार",
    chemical: "रासायनिक उपचार",
    prevention: "दीर्घकालीन प्रतिबंधात्मक उपाय",
    sampleDiseasedPhotos: "रोगाचा सराव करण्यासाठी नमुना फोटोवर क्लिक करा",

    // Chat Screen
    aiAgronomistExpertChat: "एआई कृषी तज्ञ चॅट",
    askFarmingQuestion: "कीटक नियंत्रण, खतांची मात्रा किंवा सिंचनाबद्दल कोणताही प्रश्न विचारा",
    messagePlaceholder: "पिवळी पाने, खतांच्या मात्रेबद्दल विचारा...",
    typing: "कृषी वैज्ञानिक विश्लेषण करत आहेत...",

    // Market Intelligence
    marketIntelMandi: "बाजार भाव आणि माहिती",
    marketIntelDesc: "अचूक बाजार भाव, कृषी उत्पन्न बाजार समितीचे दर आणि नफा अंदाज",
    liveIndex: "थेट बाजार दर",
    syncPrices: "बाजार दर सिंक करा",
    syncSuccessPrices: "बाजार दर यशस्वीरित्या स्थानिक स्टोरेजमध्ये साठवले गेले आहेत। ऑफलाइन गणना तयार आहे।",
    commoditySelector: "पीक निवडा",
    mandiPriceTrends: "बाजार समितीतील दर",
    mandiName: "बाजार समितीचे नाव",
    currentPrice: "सध्याचा दर (प्रति क्विंटल)",
    dailyChange: "दैनिक बदल",
    profitabilityCalc: "लागत आणि नफा कॅल्क्युलेटर",
    acresLabel: "एकूण जमीन (एकडमध्ये)",
    expectedYieldLabel: "अपेक्षित उत्पादन (क्विंटल/एकर)",
    costPerAcreLabel: "उत्पादन खर्च (₹/एकर)",
    estimatedRevenue: "अंदाजे एकूण उत्पन्न",
    netProfitMargin: "निव्वळ नफा टक्केवारी",
    netProfit: "निव्वळ नफा",

    // About Us
    ourVisionStory: "आमचा दृष्टिकोन आणि कथा",
    visionTitle: "महाराष्ट्राच्या आणि देशाच्या शेतीचे भविष्य उज्ज्वल करणे।",
    visionDesc: "पारंपरिक कृषी ज्ञानाला प्रगत एआय तंत्रज्ञानाची जोड देऊन शेतकऱ्यांचे जीवनमान उंचावणे।",
    originStory: "मूळ कहाणी",
    fromVisionToVitality: "दृष्टिकोनातून प्रत्यक्षात",
    originDesc1: "फसल डॉक्टरची सुरुवात शेतीच्या ग्रामीण भागातून झाली। शेतकऱ्यांना हवामान बदल, कीड आणि वाजारातील दलालांमुळे होणारे नुकसान पाहून आम्ही शेतकऱ्यांसाठी खिशातील सल्लागार तयार करण्याचे ठरवले।",
    originDesc2: "अचूक स्थानिक हवामानाला जेमिनी एआय मॉडेलशी जोडून आम्ही पिकांचे अचूक निदान करतो आणि उपाय सुचवतो, ज्यामुळे शेतीतील अनिश्चितता कायमची दूर होते।",
    coreValues: "मुख्य वैज्ञानिक आधारस्तंभ",
    value1Title: "कृषी सत्यता",
    value1Desc: "प्रत्येक सेंद्रिय आणि रासायनिक खताचा सल्ला कृषी विद्यापीठांच्या संशोधनावर आधारित वैज्ञानिक स्वरूपाचा आहे।",
    value2Title: "डिजिटल सुलभता",
    value2Desc: "विविध प्रादेशिक भाषा, स्पष्ट लेखन आणि स्थानिक आवाजातील संदेशांचे उत्तम साहाय्य।",
    value3Title: "ऑफलाइन सक्षमता",
    value3Desc: "आमचे स्थानिक इंजिन इंटरनेट नसतानाही थेट शेतात उत्तम काम करते।"
  },
  Telugu: {
    // Nav & Shell
    home: "హోమ్",
    diagnosis: "రోగ నిర్ధారణ",
    assistant: "సహాయకుడు",
    insights: "వాతావరణం",
    market: "మార్కెట్ ధరలు",
    mission: "లక్ష్యం",
    online: "ఆన్‌లైన్",
    offline: "ఆఫ్‌లైన్",
    logout: "లాగ్అవుట్",
    backToHome: "హోమ్ కు తిరిగి వెళ్ళు",
    chooseLanguage: "భాషను ఎంచుకోండి",
    languageSuffix: "భాష",
    namaste: "నమస్తే",
    farmOverviewFor: "ఇక్కడ మీ పొలం పరిస్థితి యొక్క అవలోకనం ఉంది",
    offlineModeActive: "ఆఫ్‌లైన్ మోడ్ యాక్టివ్‌గా ఉంది",
    offlineModeDesc: "మీరు ప్రస్తుతం ఆఫ్‌లైన్‌లో ఉన్నారు। వాతావరణం, పంటల వివరాలు మరియు మార్కెట్ ధరలు స్థానిక నిల్వ నుండి చూపించబడుతున్నాయి।",

    // Landing Page
    landingTitle: "భారతీయ వ్యవసాయ భవిష్యత్తును సుసంపన్నం చేయడం",
    landingSubtitle: "రైతుల జీవనోపాధి మరియు పంటల రక్షణ కోసం సంప్రదాయ వ్యవసాయ జ్ఞానాన్ని అత్యాధునిక ఏఐ సాంకేతికతతో అనుసంధానించడం।",
    startFarming: "వ్యవసాయం ప్రారంభించండి",
    features: "ఫీచర్లు",
    howItWorks: "ఇది ఎలా పనిచేస్తుంది",
    successStories: "విజయ గాథలు",
    ourMission: "మా లక్ష్యం",
    aiCropDoctor: "ఏఐ పంట డాక్టర్",
    aiCropDoctorDesc: "మీ ఫోన్ కెమెరాతో పంట వ్యాధులను వెంటనే గుర్తించి, ధృవీకరించబడిన సేంద్రీయ మరియు రసాయన చికిత్సలను పొందండి।",
    hyperLocalWeather: "స్థానిక వాతావరణం",
    hyperLocalWeatherDesc: "మీ ప్రాంతానికి అనుగుణంగా నిజ-సమయ వాతావరణ వవరాలు, నేల తేమ మరియు పురుగుమందుల పిచికారీకి అనువైన సమయ సమాచారం పొందండి।",
    mandiPrices: "మార్కెట్ ధరలు",
    mandiPricesDesc: "మీ స్థానిక మార్కెట్ కమిటీల పారదర్శక ధరల వివరాలతో ఎల్లప్పుడూ ముందంజలో ఉండండి మరియు పంట లాభాలను లెక్కించండి।",
    voiceAssist: "వాయిస్ సహాయం",
    voiceAssistDesc: "స్వయంచాలక స్పష్టమైన వాయిస్ సహాయంతో మీ మాతృభాషలోనే శాస్త్రీయ వ్యవసాయ సలహాలను వినండి।",

    // Login Screen
    farmerLogin: "రైతు లాగిన్",
    enterPhone: "మీ మొబైల్ నంబర్ నమోదు చేయండి",
    sendOtp: "ఓటీపీ పంపండి",
    verifyOtp: "ఓటీపీ ధృవీకరించండి",
    agreeTerms: "కొనసాగడం ద్వారా, మీరు మా సేవా నిబంధనలు మరియు గోప్యతా విధానాన్ని అంగీకరిస్తున్నారు।",
    phonePlaceholder: "10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి",
    otpSent: "మీ మొబైల్ నంబర్‌కు ఓటీపీ పంపబడింది",
    verifyAndLogin: "ధృవీకరించి లాగిన్ అవ్వండి",

    // Language Step
    onboardingChooseLanguage: "మీ భాషను ఎంచుకోండి",
    onboardingChooseLanguageDesc: "వ్యక్తిగతీకరించిన వ్యవసాయ సలహాలు, మార్కెట్ వివరాలు మరియు వాయిస్ మార్గదర్శకత్వం కోసం మీ మాతృభాషను ఎంచుకోండి।",
    detectingLocation: "పొలం స్థానాన్ని గుర్తిస్తోంది...",
    locationDetected: "పొలం స్థానం విజయవంతంగా గుర్తించబడింది",
    nextStep: "తదుపరి అడుగు",

    // Crop Step
    whatAreYouGrowing: "మీరు ఏమి పండిస్తున్నారు?",
    selectCropsDesc: "మీ పంట వ్యాధి నిర్ధారణ, వాతావరణ సూచికలు మరియు మార్కెట్ ధరలను మీ పంటకు అనుకూలంగా మార్చడానికి పంటలను ఎంచుకోండి।",
    back: "వెనుకకు",

    // Profile Step
    completeProfile: "రైతు ప్రొఫైల్ పూర్తి చేయండి",
    enterName: "మీ పేరు నమోదు చేయండి",
    enterNamePlaceholder: "ఉదా. రమేష్ కుమార్",
    voiceGuided: "వాయిస్ మార్గదర్శక సహాయం",
    voiceGuidedDesc: "నా ప్రాంతీయ భాషలో వ్యాధి నిర్ధారణ మరియు వాతావరణ హెచ్చరికలను స్వయంచాలకంగా చదివి వినిపించండి",
    submitEnterFarm: "సమర్పించి ప్రవేశించండి",

    // Dashboard
    liveFarmClimate: "పొలం వాతావరణం",
    overcastClouds: "మేఘావృతం",
    humidity: "తేమ",
    wind: "గాలి వేగం",
    uvIndex: "యువీ సూచిక",
    spraySuitability: "పిచికారీ అనుకూలత",
    highIdeal: "చాలా అనుకూలం / ఉత్తమ",
    sprayAdvisoryText: "గాలి వేగం తక్కువగా (8 కిమీ/గం) మరియు ఉష్ణోగ్రత 35 డిగ్రీల కంటే తక్కువగా ఉంది। తేమ అనుకూలంగా ఉంది। పిచికారీ చేయడానికి ఇది సరైన సమయం!",
    targetHours: "అనువైన సమయం",
    cropHealthStatus: "ప్రధాన పంట ఆరోగ్య స్థితి",
    diagnoseLeaf: "ఆకును పరీక్షించండి",
    consultExpert: "నిపుణుల సలహా",
    status: "స్థితి",
    yield: "దిగుబడి",
    estimatedValue: "అంచనా విలువ",
    riskIndex: "ప్రమాద సూచిక",
    healthy: "ఆరోగ్యంగా ఉంది",
    yellowLeafWarn: "ఆకులు పసుపు రంగులోకి మారడం",
    lowRisk: "తక్కువ ప్రమాదం",
    mediumRisk: "మధ్యస్థ ప్రమాదం",
    highRisk: "ఎక్కువ ప్రమాదం",
    cropAdvisoryPrescription: "పంట సలహాలు మరియు సూచనలు",
    advisoryAlert: "48 గంటల్లో భారీ వర్ష సూచన ఉంది। ఎరువులు కొట్టుకుపోకుండా ఉండటానికి యూరియా వేయడం వాయిదా వేయండి।",
    todayAction: "ఈరోజు కార్యాచరణ ప్రణాళిక",
    advisoryAction1: "వరి పంట పిలకలు తొడిగే దశలో 2-3 అంగుళాల నీరు ఉండేలా చూసుకోండి।",
    advisoryAction2: "తెగులు లేదా ఆకులపై మచ్చల గుర్తులను గుర్తించడానికి పంటల క్రింది భాగాలను తనిఖీ చేయండి।",
    activeCropTrack: "సజీవ పంట విశ్లేషణ",
    cultivatedCrop: "పండించిన పంట",
    yieldPrediction: "దిగుబడి అంచనా",
    estimatedMarketValue: "అంచనా మార్కెట్ విలువ",
    checkMandiRates: "మార్కెట్ ధరలు చూడండి",
    optimalIrrigation: "అనుకూల నీటి పారుదల",
    irrigationAdvisoryText: "నేల తేమ ప్రస్తుతం 32% ఉంది। రాబోయే 48 గంటల వరకు నీటి తడి అవసరం లేదు। శుక్రవారం వర్ష సూచన ఉంది।",
    viewMoistureChart: "తేమ చార్ట్ చూడండి",
    nitrogenUreaLevel: "నత్రజని మరియు యూరియా శాతం",
    nitrogenAdvisoryText: "పత్రహరితం శాతం అనుకూలంగా ఉంది। 4వ వారంలో ఎకరానికి 20 కిలోల యూరియా పిచికారీ చేయాలని సూచించబడింది।",
    askCropAssistant: "సహాయకుడిని అడగండి",
    outbreakPestForecast: "తెగులు సోకే అంచనా",
    regionalStemBorerWarning: "కాండం తొలుచు పురుగు ప్రాంతీయ హెచ్చరిక",
    stemBorerAdvisoryText: "ఎక్కువ తేమ శాతం ఉండటం వల్ల కాండం తొలుచు పురుగు సోకే అవకాశం ఉంది। ప్రమాద స్థాయి: ",
    initiateAiLeafScan: "ఇప్పుడే ఏఐ ఆకు స్కానింగ్ ప్రారంభించండి",
    smartFarmTodos: "పొలంలో చేయవలసిన పనులు",
    scanWestLeafZone: "పశ్చిమ ప్రాంతంలో ఆకులను పరీక్షించండి",
    pendingScan: "పరీక్షించవలసి ఉంది",
    scanButton: "పరీక్షించు",
    addUreaTopdress: "20 కిలోల యూరియా వేయండి",
    sowingWeek4: "విత్తిన 4వ వారం",
    week4Label: "4వ వారం",
    dailyUpdate: "రోజువారీ అప్‌డేట్",
    whatToPlantNext: "తర్వాత ఏ పంట వేయాలి?",
    durumWheat: "గోధుమ రకాలు",
    optimalSowing: "విత్తుకోవడానికి సరైన సమయం:",
    novemberRabi: "నవంబర్ (రబీ కాలం)",
    estimatedDemand: "అంచనా వేసిన డిమాండ్:",
    veryHigh: "చాలా ఎక్కువ (+12%)",
    durumWheatAdvisoryText: "ప్రపంచ మార్కెట్లో గోధుమ నిల్వలు తక్కువగా ఉండటం వల్ల, మార్కెట్లలో కనీస మద్దతు ధర కంటే 15% ఎక్కువ ధర లభించే అవకాశం ఉంది। సిఫార్సు చేసిన రకం: హెచ్‌డి 3086।",

    // Weather Insights
    weatherSoilInsights: "వాతావరణం మరియు నేల సమాచారం",
    weatherSoilDesc: "స్థానిక వాతావరణ సలహాలు, నేల తేమ, ఉష్ణోగ్రత మరియు ముందస్తు అంచనాలు",
    liveSynced: "లైవ్ అప్‌డేట్ చేయబడింది",
    offlineCache: "ఆఫ్‌లైన్ సమాచారం చూస్తున్నారు",
    syncWeather: "వాతావరణాన్ని అప్‌డేట్ చేయి",
    syncing: "అప్‌డేట్ అవుతోంది...",
    syncSuccessWeather: "పంటల డేటాబేస్ విజయవంతంగా అప్‌డేట్ చేయబడింది మరియు ఆఫ్‌లైన్ ఉపయోగం కోసం భద్రపరచబడింది।",
    rainAdvisory: "స్మార్ట్ వర్షపు హెచ్చరిక",
    heavyRainAlert: "2 రోజుల్లో భారీ వర్ష సూచన। నీటి కాలువలను వెంటనే క్లియర్ చేయండి।",
    soilTelemetry: "నేల సద్యఃస్థితి",
    soilMoisture: "నేల తేమ",
    soilTemp: "నేల ఉష్ణోగ్రత",
    statusFavorable: "స్థితి: అనుకూలం",
    idealForTillering: "పంట పెరుగుదలకు చాలా ఉత్తమం",
    sevenDayForecast: "7 రోజుల వాతావరణ మరియు పిచికారీ అంచనా",
    day: "రోజు",
    temp: "ఉష్ణోగ్రత",
    condition: "వాతావరణం",
    rainProb: "వర్షపు అవకాశం",
    windSpeed: "గాలి వేగం",

    // Diagnosis Screen
    aiCropScanner: "ఏఐ పంట తెగులు స్కానర్",
    aiCropScannerDesc: "వ్యాధి సోకిన మొక్క ఆకు ఫోటో తీయండి లేదా అప్‌లోడ్ చేయండి। మా జెమిని ఏఐ తెగులును గుర్తించి తగిన చికిత్సను సూచిస్తుంది।",
    offlineModelEngaged: "ఆఫ్‌లైన్ నిపుణుల మోడ్ యాక్టివ్",
    selectCrop: "పంటను ఎంచుకోండి",
    describeSymptoms: "లక్షణాలను వివరించండి (ఐచ్ఛికం)",
    describeSymptomsPlaceholder: "ఉదా। ఆకులపై చిన్న గోధుమ రంగు మచ్చలు, అంచులు పసుపు రంగులోకి మారడం, తెల్లటి బూజు...",
    uploadLeafImage: "ఆకు ఫోటోను అప్‌లోడ్ చేయండి",
    dragDropOrClick: "ఆకు ఫోటోను ఇక్కడ లాగండి లేదా ఎంచుకోవడానికి క్లిక్ చేయండి",
    runningDiagnostic: "తెగులు నిర్ధారణ జరుగుతోంది...",
    analyzingFoliage: "ఆకుల నమూనాల విశ్లేషణ మరియు నిపుణుల సూచనలతో సరిపోల్చడం...",
    geminiAiAgronomist: "జెనిని ఏఐ వ్యవసాయ శాస్త్రవేత్త",
    offlineLocalHeuristics: "ఆఫ్‌లైన్ స్థానిక నిపుణుడు",
    localExpertPrescription: "స్థానిక నిపుణుల సలహా పత్రం",
    diagnosticPrescriptionSheet: "వ్యాధి నిర్ధారణ మరియు చికిత్స పత్రం",
    analysisConfidence: "తెగులు ఖచ్చితత్వం స్కోరు",
    symptoms: "గమనించిన లక్షణాలు",
    causes: "తెగులు మరియు రావడానికి గల కారణాలు",
    treatment: "శాస్త్రీయ చికిత్స మరియు యాజమాన్యం",
    organic: "సేంద్రీయ చికిత్స",
    chemical: "రసాయన చికిత్స",
    prevention: "దీర్ఘకాలిక నివారణ చర్యలు",
    sampleDiseasedPhotos: "వ్యాధిని అనుకరించడానికి నమూనా ఫోటోపై క్లిక్ చేయండి",

    // Chat Screen
    aiAgronomistExpertChat: "ఏఐ వ్యవసాయ నిపుణుల చాట్",
    askFarmingQuestion: "పురుగుల నివారణ, ఎరువుల మోతాదు లేదా నీటి యాజమాన్యం గురించి ఏదైనా ప్రశ్న అడగండి",
    messagePlaceholder: "పసుపు ఆకులు, ఎరువుల మోతాదుల గురించి అడగండి...",
    typing: "వ్యవసాయ శాస్త్రవేత్త విశ్లేషిస్తున్నారు...",

    // Market Intelligence
    marketIntelMandi: "మార్కెట్ సమాచారం మరియు ధరలు",
    marketIntelDesc: "నిజ-సమయ మార్కెట్ ధరలు, వివిధ మార్కెట్ కమిటీల ధరల సరళి మరియు లాభాల అంచనా",
    liveIndex: "లైవ్ ధరలు",
    syncPrices: "ధరలను అప్‌డేట్ చేయి",
    syncSuccessPrices: "మార్కెట్ ధరలు విజయవంతంగా స్థానిక నిల్వలో భద్రపరచబడ్డాయి। ఆఫ్‌లైన్ లెక్కలు సిద్ధంగా ఉన్నాయి।",
    commoditySelector: "పంటను ఎంచుకోండి",
    mandiPriceTrends: "మార్కెట్ కమిటీల ధరలు",
    mandiName: "మార్కెట్ పేరు",
    currentPrice: "ప్రస్తుత ధర (క్వింటాల్‌కు)",
    dailyChange: "రోజువారీ మార్పు",
    profitabilityCalc: "పెట్టుబడి మరియు లాభాల క్యాలిక్యులేటర్",
    acresLabel: "భూమి విస్తీర్ణం (ఎకరాలలో)",
    expectedYieldLabel: "ఆశించిన దిగుబడి (క్వింటాల్/ఎకరాకు)",
    costPerAcreLabel: "పెట్టుబడి ఖర్చు (₹/ఎకరాకు)",
    estimatedRevenue: "అంచనా వేసిన మొత్తం ఆదాయం",
    netProfitMargin: "నికర లాభం శాతం",
    netProfit: "నికర లాభం",

    // About Us
    ourVisionStory: "మా దృక్పథం మరియు కథ",
    visionTitle: "భారతీయ వ్యవసాయ భవిష్యత్తును సరికొత్తగా తీర్చిదిద్దడం।",
    visionDesc: "రైతుల జీవనోపాధిని పటిష్టం చేయడానికి సాంప్రదాయ వ్యవసాయ పద్ధతులకు ఏఐ సాంకేతికతను జోడించడం।",
    originStory: "అసలు కథ",
    fromVisionToVitality: "కల నిజమైన వేళ",
    originDesc1: "వ్యవసాయ ప్రధాన ప్రాంతాల్లో రైతుల సమస్యలు, అకాల వాతావరణ పరిస్థితులు, దళారుల బెడదను గమనించిన తర్వాత, రైతుల చేతిలోనే ఒక నిపుణుడు ఉండేలా ఈ యాప్‌ను రూపొందించాము।",
    originDesc2: "సరికొత్త వాతావరణ అంచనాలను జెమిని ఏఐ మోడల్స్‌తో అనుసంధానించడం ద్వారా, మేము కొన్ని క్షణాల్లో ఖచ్చితమైన పంట తెగులు నిర్ధారణ మరియు చికిత్సలను అందిస్తాము।",
    coreValues: "ముఖ్యమైన శాస్త్రీయ సూత్రాలు",
    value1Title: "వ్యవసాయ విశ్వసనీయత",
    value1Desc: "ప్రతి ఎరువులు మరియు సేంద్రీయ సలహాలు వ్యవసాయ విశ్వవిద్యాలయాల పరిశోధనల ఆధారంగా శాస్త్రियంగా రూపొందించబడ్డాయి।",
    value2Title: "డిజిటల్ ప్రాప్యత",
    value2Desc: "వివిధ ప్రాంతీయ భాషల సపోర్ట్, స్పష్టమైన వచనం మరియు వాయిస్ సందేశాల ద్వారా సులభమైన యాక్సెస్।",
    value3Title: "ఆఫ్‌లైన్ సామర్థ్యం",
    value3Desc: "మా స్థానిక ఇంజిన్ ఇంటర్నెట్ లేని మారుమూల పొలాల్లో కూడా అద్భుతంగా పనిచేస్తుంది।"
  },
  Bengali: {
    // Nav & Shell
    home: "হোম",
    diagnosis: "রোগ নির্ণয়",
    assistant: "সহকারী",
    insights: "আবহাওয়া",
    market: "বাজার দর",
    mission: "আমাদের লক্ষ্য",
    online: "অনলাইন",
    offline: "অফলাইন",
    logout: "লগআউট",
    backToHome: "হোমে ফিরে যান",
    chooseLanguage: "ভাষা পরিবর্তন করুন",
    languageSuffix: "ভাষা",
    namaste: "নমস্কার",
    farmOverviewFor: "এখানে আপনার খামারের বর্তমান অবস্থার বিবরণ রয়েছে",
    offlineModeActive: "অফলাইন মোড সক্রিয়",
    offlineModeDesc: "আপনি বর্তমানে অফলাইনে আছেন। আবহাওয়া, ফসলের বিবরণ এবং বাজার দর স্থানীয় স্টোরেজ থেকে দেখানো হচ্ছে।",

    // Landing Page
    landingTitle: "ভারতীয় কৃষির ভবিষ্যৎ সুরক্ষিত করা",
    landingSubtitle: "কৃষকদের জীবিকা ও ফলন রক্ষার জন্য ঐতিহ্যবাহী কৃষিজ্ঞানের সঙ্গে আধুনিক এআই প্রযুক্তির মেলবন্ধন।",
    startFarming: "চাষাবাদ শুরু করুন",
    features: "বৈশিষ্ট্যসমূহ",
    howItWorks: "এটি কীভাবে কাজ করে",
    successStories: "সাফল্যের গল্প",
    ourMission: "আমাদের মিশন",
    aiCropDoctor: "এআই ফসল ডাক্তার",
    aiCropDoctorDesc: "আপনার ফোনের ক্যামেরা দিয়ে ফসলের রোগ সঙ্গে সঙ্গে শনাক্ত করুন এবং সঠিক জৈব ও রাসায়নিক প্রতিকার পান।",
    hyperLocalWeather: "স্থানীয় আবহাওয়া",
    hyperLocalWeatherDesc: "আপনার এলাকার জন্য রিয়েল-টাইম আবহাওয়া তথ্য, মাটির আর্দ্রতা এবং কীটনাশক স্প্রে করার সঠিক সময় জানুন।",
    mandiPrices: "বাজারের দর",
    mandiPricesDesc: "আপনার স্থানীয় এপিএমসি মান্ডির স্বচ্ছ মূল্য সূচক সম্পর্কে সর্বদা সচেতন থাকুন এবং ফসলের মুনাফা হিসাব করুন।",
    voiceAssist: "ভয়েস সহায়তা",
    voiceAssistDesc: "স্বয়ংক্রিয় স্পষ্ট ভয়েস সহায়তার মাধ্যমে আপনার নিজস্ব ভাষায় বৈজ্ঞানিক চাষাবাদের পরামর্শ শুনুন।",

    // Login Screen
    farmerLogin: "কৃষক লগইন",
    enterPhone: "আপনার মোবাইল নম্বর লিখুন",
    sendOtp: "ওটিপি পাঠান",
    verifyOtp: "ওটিপি যাচাই করুন",
    agreeTerms: "এগিয়ে যাওয়ার মাধ্যমে, আপনি আমাদের পরিষেবার শর্তাবলী এবং গোপনীয়তা নীতির সাথে সম্মত হচ্ছেন।",
    phonePlaceholder: "১০ অঙ্কের মোবাইল নম্বর লিখুন",
    otpSent: "আপনার নম্বরে একটি ওটিপি পাঠানো হয়েছে",
    verifyAndLogin: "যাচাই করুন এবং লগইন করুন",

    // Language Step
    onboardingChooseLanguage: "আপনার ভাষা নির্বাচন করুন",
    onboardingChooseLanguageDesc: "ব্যক্তিগতকৃত কৃষি পরামর্শ, বাজারের তথ্য এবং ভয়েস নির্দেশিকার জন্য আপনার মাতৃভাষা বেছে নিন।",
    detectingLocation: "খামারের অবস্থান খোঁজা হচ্ছে...",
    locationDetected: "খামারের অবস্থান সফলভাবে সনাক্ত করা হয়েছে",
    nextStep: "পরবর্তী পদক্ষেপ",

    // Crop Step
    whatAreYouGrowing: "আপনি কী চাষ করছেন?",
    selectCropsDesc: "আপনার ফসলের রোগ নির্ণয়, আবহাওয়া এবং বাজার দর আপনার ফসল অনুযায়ী কাস্টমাইজ করতে ফসল নির্বাচন করুন।",
    back: "ফিরে যান",

    // Profile Step
    completeProfile: "কৃষক প্রোফাইল সম্পূর্ণ করুন",
    enterName: "আপনার নাম লিখুন",
    enterNamePlaceholder: "যেমন, রমেশ কুমার",
    voiceGuided: "ভয়েস নির্দেশিত সহায়তা",
    voiceGuidedDesc: "আমার আঞ্চলিক ভাষায় রোগ নির্ণয় এবং আবহাওয়ার সতর্কতা স্বয়ংক্রিয়ভাবে পড়ে শোনান",
    submitEnterFarm: "জমা দিন এবং প্রবেশ করুন",

    // Dashboard
    liveFarmClimate: "লাইভ খামারের আবহাওয়া",
    overcastClouds: "মেঘলা আকাশ",
    humidity: "আর্দ্রতা",
    wind: "বাতাসের গতি",
    uvIndex: "ইউভি সূচক",
    spraySuitability: "স্প্রে করার উপযুক্ততা",
    highIdeal: "অত্যন্ত উপযুক্ত / ওর্দশ",
    sprayAdvisoryText: "বাতাসের গতি কম (৮ কিমি/ঘণ্টা) এবং তাপমাত্রা ৩৫° সে-এর নিচে রয়েছে। আর্দ্রতা অনুকূল। স্প্রে করার এটিই উপযুক্ত সময়!",
    targetHours: "উপযুক্ত সময়",
    cropHealthStatus: "প্রধান ফসলের স্বাস্থ্য পরিস্থিতি",
    diagnoseLeaf: "পাতা পরীক্ষা করুন",
    consultExpert: "বিশেষজ্ঞের পরামর্শ",
    status: "অবস্থা",
    yield: "ফলন",
    estimatedValue: "আনুমানিক মূল্য",
    riskIndex: "ঝুঁকি সূচক",
    healthy: "সুস্থ ও স্বাভাবিক",
    yellowLeafWarn: "হলুদ পাতার সতর্কতা",
    lowRisk: "কম ঝুঁকি",
    mediumRisk: "মাঝারি ঝুঁকি",
    highRisk: "উচ্চ ঝুঁকি",
    cropAdvisoryPrescription: "ফসল পরামর্শ ও ব্যবস্থাপত্র",
    advisoryAlert: "৪৮ ঘণ্টার মধ্যে ভারী বৃষ্টির পূর্বাভাস। সার ধুয়ে যাওয়া এড়াতে ইউরিয়া প্রয়োগ পিছিয়ে দিন।",
    todayAction: "আজকের কর্মপরিকল্পনা",
    advisoryAction1: "ধানের ফলন বৃদ্ধির জন্য জমিতে ২-৩ ইঞ্চি জল ধরে রাখা নিশ্চিত করুন।",
    advisoryAction2: "ধসা রোগ বা পাতার দাগের প্রাথমিক লক্ষণ সনাক্ত করতে ফসলের নিচের অংশ পরীক্ষা করুন।",
    activeCropTrack: "সক্রিয় ফসল বিশ্লেষণ",
    cultivatedCrop: "চাষ করা ফসল",
    yieldPrediction: "আনুমানিক ফলন",
    estimatedMarketValue: "আনুমানিক বাজার দর",
    checkMandiRates: "বাজার দর দেখুন",
    optimalIrrigation: "অনুকূল সেচ",
    irrigationAdvisoryText: "মাটির আর্দ্রতা বর্তমানে ৩২%। আগামী ৪৮ ঘণ্টার মধ্যে সেচের প্রয়োজন নেই। শুক্রবার বৃষ্টির সম্ভাবনা রয়েছে।",
    viewMoistureChart: "আর্দ্রতা চার্ট দেখুন",
    nitrogenUreaLevel: "নাইট্রোজেন এবং ইউরিয়ার মাত্রা",
    nitrogenAdvisoryText: "ক্লোরোফিল মাত্রা অনুকূল রয়েছে। চতুর্থ সপ্তাহে প্রতি একরে ২০ কেজি ইউরিয়া প্রয়োগের পরামর্শ দেওয়া হচ্ছে।",
    askCropAssistant: "সহকারীকে জিজ্ঞাসা করুন",
    outbreakPestForecast: "কীটপতঙ্গের আক্রমণ পূর্বাভাস",
    regionalStemBorerWarning: "মাজরা পোকার আঞ্চলিক সতর্কতা",
    stemBorerAdvisoryText: "উচ্চ আর্দ্রতার কারণে মাজরা পোকার আক্রমণ হতে পারে। আক্রমণের ঝুঁকি: ",
    initiateAiLeafScan: "এখনই এআই পাতা স্ক্যান করুন",
    smartFarmTodos: "খামারের গুরুত্বপূর্ণ কাজ",
    scanWestLeafZone: "পশ্চিম ভাগের পাতার পরীক্ষা করুন",
    pendingScan: "পরীক্ষা বাকি রয়েছে",
    scanButton: "পরীক্ষা",
    addUreaTopdress: "২০ কেজি ইউরিয়া প্রয়োগ করুন",
    sowingWeek4: "রোপণের চতুর্থ সপ্তাহ",
    week4Label: "চতুর্থ সপ্তাহ",
    dailyUpdate: "দৈনিক আপডেট",
    whatToPlantNext: "পরবর্তী ফসল কী বোবেন?",
    durumWheat: "গমের উন্নত জাত",
    optimalSowing: "রোপণের সঠিক সময়:",
    novemberRabi: "নভেম্বর (রবি মরশুম)",
    estimatedDemand: "আনুমানিক চাহিদা:",
    veryHigh: "খুব বেশি (+12%)",
    durumWheatAdvisoryText: "বিশ্ব বাজারে কম মজুদের কারণে, গমের উন্নত জাত মান্ডিতে এমএসপির চেয়ে ১৫% বেশি দরে বিক্রি হতে পারে। সুপারিশকৃত জাত: এইচডি ৩০৮৬।",

    // Weather Insights
    weatherSoilInsights: "আবহাওয়া এবং মাটির তথ্য",
    weatherSoilDesc: "স্থানীয় আবহাওয়া পরামর্শ, মাটির আর্দ্রতা, তাপমাত্রা এবং পূর্বাভাস",
    liveSynced: "লাইভ সিঙ্ক করা হয়েছে",
    offlineCache: "অফলাইন তথ্য দেখছেন",
    syncWeather: "আবহাওয়া আপডেট করুন",
    syncing: "আপডেট হচ্ছে...",
    syncSuccessWeather: "ফসল ডেটাবেস সফলভাবে আপডেট করা হয়েছে এবং অফলাইন ব্যবহারের জন্য সুরক্ষিত করা হয়েছে।",
    rainAdvisory: "স্মার্ট বৃষ্টি সতর্কতা",
    heavyRainAlert: "২ দিনের মধ্যে ভারী বৃষ্টির পূর্বাভাস। জল নিষ্কাশনের পথ দ্রুত পরিষ্কার করুন।",
    soilTelemetry: "মাটির বর্তমান অবস্থা",
    soilMoisture: "মাটির আর্দ্রতা",
    soilTemp: "মাটির তাপমাত্রা",
    statusFavorable: "অবস্থা: অনুকূল",
    idealForTillering: "ফসলের বৃদ্ধির জন্য আদর্শ",
    sevenDayForecast: "৭ দিনের আবহাওয়া এবং স্প্রে করার উপযুক্ততার পূর্বাভাস",
    day: "দিন",
    temp: "তাপমাত্রা",
    condition: "আবহাওয়া",
    rainProb: "বৃষ্টির সম্ভাবনা",
    windSpeed: "বাতাসের গতি",

    // Diagnosis Screen
    aiCropScanner: "এআই ফসল রোগ স্ক্যানার",
    aiCropScannerDesc: "আক্রান্ত গাছের পাতার ছবি তুলুন বা আপলোড করুন। আমাদের জেমিনি এআই রোগ সনাক্ত করে প্রতিকার জানাবে।",
    offlineModelEngaged: "অফলাইন বিশেষজ্ঞ মডেল সক্রিয়",
    selectCrop: "ফসল নির্বাচন করুন",
    describeSymptoms: "লক্ষণ বর্ণনা করুন (ঐচ্ছিক)",
    describeSymptomsPlaceholder: "যেমন, পাতায় ছোট ছোট বাদামী দাগ, পাতার কিনারা হলুদ হওয়া, সাদা ছত্রাক...",
    uploadLeafImage: "পাতার ছবি আপলোড করুন",
    dragDropOrClick: "পাতার ছবি এখানে ড্র্যাগ করুন অথবা সিলেক্ট করতে ক্লিক করুন",
    runningDiagnostic: "রোগ নির্ণয় করা হচ্ছে...",
    analyzingFoliage: "পাতার প্যাটার্ন বিশ্লেষণ এবং কৃষি বিশেষজ্ঞদের নিয়মের সাথে মিলানো হচ্ছে...",
    geminiAiAgronomist: "জেমিনি এআই কৃষি বিজ্ঞানী",
    offlineLocalHeuristics: "অফলাইন স্থানীয় বিশেষজ্ঞ",
    localExpertPrescription: "স্থানীয় বিশেষজ্ঞ ব্যবস্থাপত্র",
    diagnosticPrescriptionSheet: "রোগ নির্ণয় এবং ব্যবস্থাপত্র",
    analysisConfidence: "রোগের নির্ভুলता স্কোর",
    symptoms: "লক্ষণসমূহ",
    causes: "রোগের কারণ ও ছত্রাক",
    treatment: "বৈজ্ঞানিক চিকিৎসা ও ব্যবস্থাপনা",
    organic: "জৈব চিকিৎসা",
    chemical: "রাসায়নিক চিকিৎসা",
    prevention: "দীর্ঘমেয়াদী প্রতিরোধ ব্যবস্থা",
    sampleDiseasedPhotos: "রোগের অনুকরণ করতে একটি নমুনা ছবিতে ক্লিক করুন",

    // Chat Screen
    aiAgronomistExpertChat: "এআই কৃষি বিশেষজ্ঞ চ্যাপ",
    askFarmingQuestion: "কীটপতঙ্গ নিয়ন্ত্রণ, সারের মাত্রা বা সেচ সম্পর্কিত যে কোনও প্রশ্ন জিজ্ঞাসা করুন",
    messagePlaceholder: "হলুদ পাতা, সারের প্রয়োগ সম্পর্কে জিজ্ঞাসা করুন...",
    typing: "কৃষি বিজ্ঞানী বিশ্লেষণ করছেন...",

    // Market Intelligence
    marketIntelMandi: "বাজারের তথ্য ও মান্ডির দর",
    marketIntelDesc: "রিয়েল-টাইম বাজারের দর, এপিএমসি মান্ডির প্রবণতা এবং লাভ ক্যালকুলেটর",
    liveIndex: "লাইভ মূল্য সূচক",
    syncPrices: "দর আপডেট করুন",
    syncSuccessPrices: "বাজারের দর সফলভাবে স্থানীয় স্টোরেজে আপডেট করা হয়েছে। অফলাইন হিসাব প্রস্তুত।",
    commoditySelector: "ফসল নির্বাচন করুন",
    mandiPriceTrends: "এপিএমসি মান্ডির দর",
    mandiName: "মান্ডির নাম",
    currentPrice: "বর্তমান দর (প্রতি কুইন্টাল)",
    dailyChange: "দৈনিক পরিবর্তন",
    profitabilityCalc: "চাষের খরচ ও লাভ ক্যালকুলেটর",
    acresLabel: "মোট জমি (একর হিসেবে)",
    expectedYieldLabel: "অপেক্ষিত ফলন (কুইন্টাল/একর)",
    costPerAcreLabel: "চাষের খরচ (₹/একর)",
    estimatedRevenue: "আনুমানিক মোট আয়",
    netProfitMargin: "নিট লাভের হার",
    netProfit: "নিট লাভ",

    // About Us
    ourVisionStory: "আমাদের দৃষ্টিভঙ্গি ও গল্প",
    visionTitle: "ভারতীয় কৃষির ভবিষ্যৎ সমৃদ্ধ করা।",
    visionDesc: "কৃষকদের জীবিকা সুরক্ষিত করতে ঐতিহ্যবাহী কৃষি পদ্বতির সাথে এআই প্রযুক্তির মেলবন্ধন।",
    originStory: "মূল গল্প",
    fromVisionToVitality: "স্বপ্ন থেকে বাস্তবে",
    originDesc1: "ফসল ডাক্তারের জন্ম ভারতের কৃষিজীবী অঞ্চলের কেন্দ্রস্থলে। কৃষকদের আবহাওয়া বিপর্যয়, কীটপতঙ্গের আক্রমণ এবং ফড়িয়াদের দৌরাত্ম্যের সাথে লড়াই করতে দেখে আমরা এই পকেট সহকারীটি তৈরির সিদ্ধান্ত নিই।",
    originDesc2: "সঠিক আবহাওয়ার পূর্বাভাসের সাথে জেমিনি এআই মডেলকে যুক্ত করে আমরা মুহূর্তে ফসলের রোগ নির্ণয় এবং তার প্রতিকার জানাই, যা চাষের অনিশ্চয়তা দূর করে।",
    coreValues: "মূল বৈজ্ঞানিক স্তম্ভ",
    value1Title: "কৃষি সত্যতা",
    value1Desc: "প্রতিটি সার এবং জৈব পরামর্শ কৃষি বিশ্ববিদ্যালয়ের গবেষণার উপর ভিত্তি করে বৈজ্ঞানিকভাবে প্রস্তুত করা হয়েছে।",
    value2Title: "ডিজিটাল অন্তর্ভুক্তি",
    value2Desc: "সহজে ব্যবহারের জন্য একাধিক আঞ্চলিক ভাষা, স্পষ্ট লেখা এবং ভয়েস বার্তার চমৎকার সহায়তা।",
    value3Title: "অফলাইন সক্ষমতা",
    value3Desc: "আমাদের স্থানীয় ইঞ্জিন ইন্টারনেট সংযোগ ছাড়াই সরাসরি খামারে দারুণভাবে কাজ করে।"
  },
  Tamil: {
    home: "முகப்பு",
    diagnosis: "நோய் கண்டறிதல்",
    assistant: "உதவியாளர்",
    insights: "வானிலை",
    market: "சந்தை",
    mission: "எங்கள் நோக்கம்",
    online: "ஆன்லைன்",
    offline: "ஆஃப்லைன்",
    logout: "வெளியேறு",
    backToHome: "முகப்புக்குத் திரும்பு",
    chooseLanguage: "மாநில மொழியைத் தேர்வுசெய்",
    namaste: "வணக்கம்",
    farmerLogin: "விவசாயி உள்நுழைவு",
    enterPhone: "உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்",
    sendOtp: "OTP அனுப்பவும்",
    verifyOtp: "OTP ஐ சரிபார்க்கவும்",
    onboardingChooseLanguage: "உங்கள் மொழியைத் தேர்வுசெய்",
    whatAreYouGrowing: "நீங்கள் என்ன பயிரிடுகிறீர்கள்?",
    completeProfile: "விவசாயி சுயவிவரத்தை பூர்த்திசெய்",
    enterName: "உங்கள் பெயரை உள்ளிடவும்",
    submitEnterFarm: "சமர்ப்பித்து பண்ணைக்குள் நுழையவும்",
    aiAgronomistExpertChat: "AI விவசாய நிபுணர் அரட்டை",
    askFarmingQuestion: "பூச்சி மேலாண்மை, உர அளவு அல்லது நீர்ப்பாசனம் பற்றிய எந்தவொரு விவசாய கேள்வியையும் கேளுங்கள்",
    messagePlaceholder: "மஞ்சள் இலைகள், உர அளவு பற்றி கேளுங்கள்...",
    typing: "விவசாய நிபுணர் பகுப்பாய்வு செய்கிறார்..."
  },
  Kannada: {
    home: "ಮುಖಪುಟ",
    diagnosis: "ರೋಗ ಪತ್ತೆ",
    assistant: "ಸಹಾಯಕ",
    insights: "ಹವಾಮಾನ",
    market: "ಮಾರುಕಟ್ಟೆ",
    mission: "ನಮ್ಮ ಧ್ಯೇಯ",
    online: "ಆನ್‌ಲೈನ್",
    offline: "ಆಫ್‌ಲೈನ್",
    logout: "ನಿರ್ಗಮಿಸು",
    backToHome: "ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ",
    chooseLanguage: "ರಾಜ್ಯದ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    namaste: "ನಮಸ್ಕಾರ",
    farmerLogin: "ರೈತರ ಲಾಗಿನ್",
    enterPhone: "ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
    sendOtp: "OTP ಕಳುಹಿಸಿ",
    verifyOtp: "OTP ಪರಿಶೀಲಿಸಿ",
    onboardingChooseLanguage: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆರಿಸಿ",
    whatAreYouGrowing: "ನೀವು ಏನನ್ನು ಬೆಳೆಯುತ್ತಿದ್ದೀರಿ?",
    completeProfile: "ರೈತರ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ",
    enterName: "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
    submitEnterFarm: "ಸಲ್ಲಿಸಿ ಮತ್ತು ಫಾರ್ಮ್ ಪ್ರವೇಶಿಸಿ",
    aiAgronomistExpertChat: "AI ಕೃಷಿ ತಜ್ಞರ ಚಾಟ್",
    askFarmingQuestion: "ಕೀಟ ನಿರ್ವಹಣೆ, ರಸಗೊಬ್ಬರ ಪ್ರಮಾಣ ಅಥವಾ ನೀರಾವರಿ ಬಗ್ಗೆ ಯಾವುದೇ ಕೃಷಿ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ",
    messagePlaceholder: "ಹಳದಿ ಎಲೆಗಳು, ರಸಗೊಬ್ಬರ ಪ್ರಮಾಣ ಬಗ್ಗೆ ಕೇಳಿ...",
    typing: "ಕೃಷಿ ತಜ್ಞರು ವಿಶ್ಲೇಷಿಸುತ್ತಿದ್ದಾರೆ..."
  },
  Malayalam: {
    home: "ഹോം",
    diagnosis: "രോഗനിർണ്ണയം",
    assistant: "സഹായി",
    insights: "കാലാവസ്ഥ",
    market: "മാർക്കറ്റ്",
    mission: "ഞങ്ങളുടെ ദൗത്യം",
    online: "ഓൺലൈൻ",
    offline: "ഓഫ്‌ലൈൻ",
    logout: "ലോഗ് ഔട്ട്",
    backToHome: "വീണ്ടും ഹോമിലേക്ക്",
    chooseLanguage: "സംസ്ഥാന ഭാഷ തിരഞ്ഞെടുക്കുക",
    namaste: "നമസ്കാരം",
    farmerLogin: "കർഷക ലോഗിൻ",
    enterPhone: "നിങ്ങളുടെ മൊബൈൽ നമ്പർ നൽകുക",
    sendOtp: "OTP അയയ്ക്കുക",
    verifyOtp: "OTP സ്ഥിരീകരിക്കുക",
    onboardingChooseLanguage: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
    whatAreYouGrowing: "നിങ്ങൾ എന്താണ് കൃഷി ചെയ്യുന്നത്?",
    completeProfile: "കർഷക പ്രൊഫൈൽ പൂർത്തിയാക്കുക",
    enterName: "നിങ്ങളുടെ പേര് നൽകുക",
    submitEnterFarm: "സമർപ്പിച്ചു കൃഷിയിടത്തിലേക്ക് പ്രവേശിക്കുക",
    aiAgronomistExpertChat: "AI കാർഷിക വിദഗ്ദ്ധ ചാറ്റ്",
    askFarmingQuestion: "കീട നിയന്ത്രണം, വളപ്രയോഗം അല്ലെങ്കിൽ ജലസേചനം എന്നിവയെക്കുറിച്ച് ഏതെങ്കിലും കാർഷിക ചോദ്യങ്ങൾ ചോദിക്കുക",
    messagePlaceholder: "മഞ്ഞ ഇലകൾ, വളത്തിന്റെ അളവ് എന്നിവയെക്കുറിച്ച് ചോദിക്കുക...",
    typing: "കാർഷിക വിദഗ്ദ്ധൻ വിശകലനം ചെയ്യുന്നു..."
  },
  Gujarati: {
    home: "હોમ",
    diagnosis: "રોગ નિદાન",
    assistant: "સહાયક",
    insights: "હવામાન",
    market: "બજાર",
    mission: "અમારું લક્ષ્ય",
    online: "ઓનલાઇન",
    offline: "ઓફલાઇન",
    logout: "લોગઆઉટ",
    backToHome: "હોમ પર પાછા જાઓ",
    chooseLanguage: "રાજ્યની ભાષા પસંદ કરો",
    namaste: "નમસ્તે",
    farmerLogin: "ખેડૂત લોગિન",
    enterPhone: "તમારો મોબાઈલ નંબર દાખલ કરો",
    sendOtp: "OTP મોકલો",
    verifyOtp: "OTP ચકાસો",
    onboardingChooseLanguage: "તમારી ભાષા પસંદ કરો",
    whatAreYouGrowing: "તમે શું ઉગાડી રહ્યા છો?",
    completeProfile: "ખેડૂત પ્રોફાઇલ પૂર્ણ કરો",
    enterName: "તમારું નામ દાખલ કરો",
    submitEnterFarm: "સબમિટ કરો અને ખેતરમાં પ્રવેશ કરો",
    aiAgronomistExpertChat: "AI કૃષિ નિષ્ણાત ચેટ",
    askFarmingQuestion: "જંતુ વ્યવસ્થાપન, ખાતર માત્રા અથવા સિંચાઈ વિશે કોઈપણ કૃષિ પ્રશ્ન પૂછો",
    messagePlaceholder: "પીળા પાંદડા, ખાતર માત્રા વિશે પૂછો...",
    typing: "કૃષિ નિષ્ણાત વિશ્લેષણ કરી રહ્યા છે..."
  },
  Odia: {
    home: "ହୋମ୍",
    diagnosis: "ରୋଗ ନିରୂପଣ",
    aiAgronomistExpertChat: "AI କୃଷି ବିଶେଷଜ୍ଞ ଚାଟ୍",
    askFarmingQuestion: "ପୋକ ନିୟନ୍ତ୍ରଣ, ସାରର ମାତ୍ରା କିମ୍ବା ଜଳସેଚନ ବିଷୟରେ ଯେକୌଣସି କୃଷି ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ",
    messagePlaceholder: "ହଳଦିଆ ପତ୍ର, ସାରର ମାત୍ରା ବିଷୟରେ ପଚାରନ୍ତୁ...",
    typing: "କୃଷି ବିଶେଷଜ୍ଞ ବିଶ୍ଳେଷଣ କରୁଛନ୍ତି...",
    assistant: "ସହାୟକ",
    insights: "ପାଣିପାଗ",
    market: "ବଜାର ଦର",
    mission: "ଆମର ଲକ୍ଷ୍ୟ",
    online: "ଅନଲାଇନ୍",
    offline: "ଅଫଲାଇନ୍",
    logout: "ଲଗ୍ ଆଉଟ୍",
    backToHome: "ହୋମକୁ ଫேରିଯାଆନ୍ତୁ",
    chooseLanguage: "ରାଜ୍ୟ ଭାଷା ଚୟନ କରନ୍ତୁ",
    namaste: "ନମସ୍କାର",
    farmerLogin: "କୃଷକ ଲଗଇନ୍",
    enterPhone: "ଆପଣଙ୍କ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ",
    sendOtp: "OTP ପଠାନ୍ତୁ",
    verifyOtp: "OTP ଯାଞ୍ચ କରନ୍ତୁ",
    onboardingChooseLanguage: "ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ",
    whatAreYouGrowing: "ଆପଣ କଣ ଚାଷ କରୁଛନ୍ତି?",
    completeProfile: "କୃଷକ ପ୍ରୋଫାଇଲ୍ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ",
    enterName: "ଆପڻଙ୍କ ନାମ ଦିଅନ୍ତୁ",
    submitEnterFarm: "ଦାଖଲ କରି ଫାର୍ମରେ ପ୍ରବେଶ କରନ୍ତୁ"
  },
  Assamese: {
    home: "হোম",
    diagnosis: "ৰোগ নিৰ্ণয়",
    assistant: "সহায়ক",
    insights: "বতৰ",
    market: "বজাৰ",
    mission: "আমাৰ লক্ষ্য",
    online: "অনলাইন",
    offline: "অফলাইন",
    logout: "লগ আউট",
    backToHome: "হোমলৈ ঘূৰি যাওক",
    chooseLanguage: "ৰাজ্যিক ভাষা বাছনি কৰক",
    namaste: "নমস্কাৰ",
    farmerLogin: "কৃষক লগইন",
    enterPhone: "আপোনাৰ মোবাইল নম্বৰ দিয়ক",
    sendOtp: "OTP পঠিয়াওক",
    verifyOtp: "OTP পৰীক্ষা কৰক",
    onboardingChooseLanguage: "আপোনাৰ ভাষা বাছনি কৰক",
    whatAreYouGrowing: "আপুনি কি খেতি কৰিছে?",
    completeProfile: "কৃষক প্ৰফাইল সম্পূৰ্ণ কৰক",
    enterName: "আপোনাৰ নাম লিখক",
    submitEnterFarm: "দাখিল কৰি ফাৰ্মত প্ৰৱেশ কৰক",
    aiAgronomistExpertChat: "AI কৃষি বিশেষজ্ঞৰ সৈতে বাৰ্তালাপ",
    askFarmingQuestion: "কীট-পতংগ নিয়ন্ত্ৰণ, সাৰৰ মাত্ৰা বা জলসিঞ্চন সম্পৰ্কে যিকোনো কৃষি বিষয়ক প্ৰশ্ন সোধক",
    messagePlaceholder: "হালধীয়া পাত, সাৰৰ প্ৰয়োগ সম্পৰ্কে সোধক...",
    typing: "কৃষি বিশেষজ্ঞই বিশ্লেষণ কৰি আছে..."
  }
};

export function t(key: string, lang: Language): string {
  const langTranslations = translations[lang] || translations.English;
  return langTranslations[key] || translations.English[key] || key;
}
